### ISSUE TITLE
Questions about plugin ?

### ISSUE THREAD

**Issue by warrenbell** [sitewaerts/cordova-plugin-document-viewer#1]
Couple of questions for you.

How new is this plugin ? 

How do I keep the options in the title bar from overlapping each other on an iPhone ?

I am mainly interested in view and print. So all I would need is a close/exit button and a print button. I like the view which is one page at a time, swipe to the right to see the next page. Can I set it up to do just this ?

Thanks,

Warren Bell

**Comment by regnete** [comment]
Hi warrenbell, 

sorry for the late answer. Here the info you requested:

```How new is this plugin ? ```

The plugin is currently under development. We already use it in one customers productive app (iOS and Android) without any known issues.

So it is brand new but some kind of stable.

```How do I keep the options in the title bar from overlapping each other on an iPhone ?```

We haven't tested the plugin on iPhone yet. I will add a feature request to the project for this. 

```I am mainly interested in view and print. So all I would need is a close/exit button and a print button. I like the view which is one page at a time, swipe to the right to see the next page. Can I set it up to do just this ?```

It tried this out in the sample app available at https://github.com/sitewaerts/cordova-plugin-document-viewer-sample-app by setting the VIEWER_OPTIONS in www/index.html to
```js
{
 documentView : { closeLabel : "Fertig"},
    navigationView : {closeLabel : "Zurück"},
    email : {
        enabled : false
    },
    print : {
        enabled : true
    },
    openWith : {
        enabled : false
    },
    bookmarks : {
        enabled : false
    },
    search : {
        enabled : false
    }
}
```

iOS: It works for me. The print icon is displayed as expected. Sadly we currently have no feature to disable any of the three display modes. So your users would be able to switch between the modes single page, double page and double pages with cover. I will add a feature request to the project for this. 

Android: The app displays a question mark as print icon. Touching the icon disptches to google cloud printing on my device, which is the intended behaviour. The question mark should be substituted by a proper icon. I will create a feature request for this. On Android the viewer (cleverdox Viewer) supports exactly one display mode, which is exactly what you are looking for.

For any feature request mentioned above: I can't determine if or when they will be delivered.Feel free to implement the feature(s) yourself an push them back to the project!

**Comment by Leeaandrob** [comment]
why not install cleverdox view together the plugin on android system?

**Comment by regnete** [comment]
as stated in the docs this is due to license issues.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 14.11.2015 um 03:52 schrieb Leandro Barbosa <notifications@github.com<mailto:notifications@github.com>>:


why not install cleverdox view together the plugin on android system?

-
