### ISSUE TITLE
Not opening pdf and no error throw

### ISSUE THREAD

**Issue by pkulcsar** [sitewaerts/cordova-plugin-document-viewer#100]
Using **Ionic View App** on iPhone and document viewer plugin. 

After downloading a pdf, tring to display it, but does not open, and any errors are thrown. 
Does not hit onError, or onMissingApp (funtciont in params on correct place)

Even in try-catch does not displays error

**Comment by regnete** [comment]
Sorry, but thats not enough info to give you a hint on how to fix your issue.
By the way: The plugin is not designed for phones but for tablets.
Did you try to reproduce  the issue with the sample app?

**Comment by hesampour** [comment]
same problem here. I catch no error. and just nothing.

**Comment by ChinniKrishna12** [comment]
@regnete Could you please help me here with the plugin functionality,.. I am able to see/load the PDF only after clicking alignment button on top right of the Document Viewer. No matter what i tried it loading the PDF on click of a button.. Really appreciate your quick response and help.

**Comment by regnete** [comment]
Again: Sorry, but thats not enough info to give you a hint on how to fix your issue.

**Comment by ChinniKrishna12** [comment]
Taking reference from your same code. I tried to implement the document viewer as below:
 OpenMessageDoc: function (messageId) {
        indexView.databaseObj.transaction(function (tx) {
            tx.executeSql('SELECT GetJSON FROM SEP_Data WHERE Module=?', ['MESSAGES'], function (tx, results) {
                if (results.rows && results.rows.length > 0) {
                    var response = JSON.parse(results.rows.item(0).GetJSON), url, messageid;
                    for (var i = 0; i < response.Messages.length; i++) {
                        if (response.Messages[i].InitiativeGuid === messageId) {
                            //if (1 === messageId) {
                            url = response.Messages[i].DocumentLocation;
                            messageid = response.Messages[i].Messageid;
                            break;
                        }
                    }
                    url = url.split('\\');
                    url = url[url.length - 1];
                    url = cordova.file.dataDirectory + '//pdf//' + messageid + '//' + url;

                    contentType = "application/pdf", options = {};
                    cordova.plugins.SitewaertsDocumentViewer.canViewDocument(url, contentType, options, function () {
                        window.console.log('document can be shown');                            //e.g. track document usage

                    }, function (appId, installer) {
                        if (confirm("Do you want to install the free PDF Viewer App "
                                    + appId + " for Android?")) {
                            installer();
                        }
                    }, function () {
                        window.console.log('document cannot be shown');
                    }, function (error) {
                        window.console.log(error);
                        alert("Sorry! Cannot show document.");

                    });

                    var mimeType = "application/pdf", linkHandlers = [];

                    cordova.plugins.SitewaertsDocumentViewer.viewDocument(url, mimeType, options, function () {
                        console.log('document shown');
                    }, function () {
                        console.log('document closed');
                    }, function (appId, installer) {
                        if (confirm("Do you want to install the free PDF Viewer App "
                                + appId + " for Android?")) {
                            installer();
                        }
                    }, function (error) {
                        console.log(error);
                    }, linkHandlers);

                }
            });
        });
    }

above is the method called on click of a button. Problem here is  on initial load PDF document was not displayed which was loaded and we can only see loading animation, But when i click on the view change on top right of the document viewer which display's the PDF.

I was clue less why the document was not loading/displaying on click event (which is calling above method mentioned above ).
