### ISSUE TITLE
Plugin requiring to install specific PDF Viewer

### ISSUE THREAD

**Issue by synga** [sitewaerts/cordova-plugin-document-viewer#101]
Hi everyone. I'm trying to use the plugin and it seems that everything is working as expected, but when using `viewDocument()` method without any callback it always open up Google Play in Sitewaerts specific PDF Viewer (Cleverdox) but i already have an PDF Viewer.

When using all callbacks in the method it always falls on the `missingApp` callback returning `de.sitewaerts.cleverdox.viewer`.

So i really need the specific PDF Viwer? Do i need to force my users to install this?

**Comment by synga** [comment]
Ok now i've read the part where it says about muPDF, sorry, tl;dr.

**Comment by lim-enhui** [comment]
muPDF is not supported for the current Android Emulator and Devices. Any other options? UXReader?
