### ISSUE TITLE
Plugin integration error - Windows 8.1

### ISSUE THREAD

**Issue by pratikshan04** [sitewaerts/cordova-plugin-document-viewer#102]
I was able to Install the plugin, on running the app this exception pops up.

![screen shot 2018-03-05 at 5 03 27 pm](https://user-images.githubusercontent.com/13994588/36973104-9a0c932e-2097-11e8-8b0d-452bac82af7a.png)

**Comment by regnete** [comment]
You could try one of the versions proir to the current (0.9.8). May be Windws 8.1 support is broken in the lateste release.
