### ISSUE TITLE
Document has changes. Save them?

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [sitewaerts/cordova-plugin-document-viewer#103]
Document has changes. Save them?

I am getting above error while opening few pdf reports. Not happening with all reports.

I didn't make changes in pdf. How can i disable this message

![issue](https://user-images.githubusercontent.com/36895131/37016363-d2320532-2131-11e8-8b97-2faf88491877.png)

**Comment by regnete** [comment]
I never faced this message. Are you able to reproduce the behaviour with the sample app? Could you please attach a sample pdf file to this issue?

**Comment by Jeyakumarrathnaselvi** [comment]
We are facing it rarely. We couldn't fix it
