### ISSUE TITLE
com.android.support v4 update breaks the plugin for Android 

### ISSUE THREAD

**Issue by BigJenson** [sitewaerts/cordova-plugin-document-viewer#105]
Hi,
this Plugin currently has the same Issue as described for the cordova-plugin-file-opener2 here:
https://github.com/pwlin/cordova-plugin-file-opener2/issues/199

Its currently not possible to build for Android without manually forking/patching this Plugin.

**Comment by goffioul** [comment]
It would be nice to have a quick release for this problem. That would avoid everybody having to fork the project.

**Comment by regnete** [comment]
Sorry. I'm currently stuck in other projects. Could anyone provide well working a pull request on that?

**Comment by goffioul** [comment]
PR #107 works for me.

**Comment by clementcontet** [comment]
Works for me too

**Comment by regnete** [comment]
published version 0.9.9 minutes ago.
thx guys,

**Comment by regnete** [comment]
for anybody having this issue in combination with other plugins:

https://github.com/dpa99c/cordova-android-support-gradle-release

https://stackoverflow.com/questions/49162823/ionic-app-cant-build-oin-android-aapt-error

**Comment by DoubleHub** [comment]
I'm still getting this error even after adding the cordova-android-support-gradle-release plugin:

`[cordova] /home/giovanni/Projects/ionic-client/platforms/android/app/src/main/java/de/sitewaerts/cordova/documentviewer/DocumentViewerPlugin.java:34: error: package android.support.v4.content does not exist
[cordova] import android.support.v4.content.FileProvider;`
