### ISSUE TITLE
Error building for Android

### ISSUE THREAD

**Issue by jondediego** [sitewaerts/cordova-plugin-document-viewer#108]
Hi,
I am trying to build for android the version 0.9.9 of this plugin.
I use cordova-android 6.2.2 version and cordova 8.0.0.
When I try to run for andoird "ionic cordova run android", I get following error:
`* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any version that matches com.android.support:support-v4:27+.
     Versions that do not match:
         26.0.0-alpha1
         25.3.1
         25.3.0
         25.2.0
         25.1.1
         + 32 more
     Searched in the following locations:
         file:/C:/Users/jdiegoa/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml
         file:/C:/Projects/GaliaMobile/branches/evolutiveClean/platforms/android/sdk-manager/com/android/support/support-v4/maven-metadata.xml
         file:/C:/Projects/GaliaMobile/branches/evolutiveClean/platforms/android/sdk-manager/com/android/support/support-v4/
     Required by:
         project :
`

Should I use another version of this plugin to be compatible with cordova-android 6.2.2?

**Comment by regnete** [comment]
Please try older versions of this plugin. We currently target cordova-android 7,1,0
