### ISSUE TITLE
invalid file url 'assets/1.pdf' or no  viewer for mime type 'application/pdf'

### ISSUE THREAD

**Issue by hesampour** [sitewaerts/cordova-plugin-document-viewer#109]
hello.
I tried a lot to run this plugin on my project. but I get the following error.
Error in SitewaertsDocumentViewer.viewDocument(): invalid file url 'assets/1.pdf' or no
            viewer for mime type 'application/pdf'. 
I changed the url to www/assets/1.pdf files:///assets/1.pdf but non of them worked
I test with real apk. ionic devApp and cordova simulate on android and non of them worked.
another quastion is that may I run this plugin with ionic serve?

**Comment by regnete** [comment]
try again with an absolute file uri

**Comment by hesampour** [comment]
would you please give me an example? I want to put my pdf file in the asset folder of my app.

**Comment by regnete** [comment]
please check out the sample app

**Comment by hesampour** [comment]
when running the sample app it just close!!!

**Comment by PixelShoot** [comment]
@hesampour For android correct path is 'file:///android_asset/www/assets/your_pdf_file.pdf' and for ios just use ``location.href.replace("/index.html", "") + '/assets/your_pdf_file.pdf'``

**Comment by Anujmoglix** [comment]
what about dynamic url ?
