### ISSUE TITLE
Plugin should use a background thread

### ISSUE THREAD

**Issue by modille** [sitewaerts/cordova-plugin-document-viewer#11]
During usage on iOS, a warning log is emitted when you view a document:

> THREAD WARNING: ['SitewaertsDocumentViewer'] took '82.083008' ms. Plugin should use a background thread.

Seems like it might be a small lift:

https://cordova.apache.org/docs/en/3.0.0/guide_platforms_ios_plugin.md.html#iOS%20Plugins_threading

``` objc
- (void)myPluginMethod:(CDVInvokedUrlCommand*)command
{
    // Check command.arguments here.
    [self.commandDelegate runInBackground:^{
        NSString* payload = nil;

        // Some blocking logic...

        CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:payload];
        // The sendPluginResult method is thread-safe.
        [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
    }];
}
```

**Comment by regnete** [comment]
Hi Matt,

currently we do not have the resources to apply changes to the code. Feel free to change the code and provide a pull request or just the changed source files as an email attachment.
We will push it to the git then.

Thank you for helping to improve the document reader plugin.

For your interest: We are planing a new release which contains basic pdf reader functionality for windows 8.1+ within the next 2 months.

Felix


Von: Matt Odille [mailto:notifications@github.com]
Gesendet: Mittwoch, 8. Juli 2015 22:46
An: sitewaerts/cordova-plugin-document-viewer
Betreff: [cordova-plugin-document-viewer] Plugin should use a background thread (#11)


During usage on iOS, a warning log is emitted when you view a document:

THREAD WARNING: ['SitewaertsDocumentViewer'] took '82.083008' ms. Plugin should use a background thread.

Seems like it might be a small lift:

https://cordova.apache.org/docs/en/3.0.0/guide_platforms_ios_plugin.md.html#iOS%20Plugins_threading

- (void)myPluginMethod:(CDVInvokedUrlCommand*)command

{

    // Check command.arguments here.

    [self.commandDelegate runInBackground:^{

        NSString* payload = nil;



        // Some blocking logic...



        CDVPluginResult* pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:payload];

        // The sendPluginResult method is thread-safe.

        [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];

    }];

}
