### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference"

### ISSUE THREAD

**Issue by pnnrahul** [sitewaerts/cordova-plugin-document-viewer#111]
{status: 9, message: "Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference", details: "java.lang.NullPointerException: Attempt to invoke …a:587)↵	at java.lang.Thread.run(Thread.java:818)↵"}
details
:
"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference↵	at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.canGetFile(DocumentViewerPlugin.java:676)↵	at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.doExecute(DocumentViewerPlugin.java:351)↵	at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.access$000(DocumentViewerPlugin.java:49)↵	at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin$1.run(DocumentViewerPlugin.java:184)↵	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)↵	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)↵	at java.lang.Thread.run(Thread.java:818)↵"
message
:
"Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference"
status
:
9

**Comment by pnnrahul** [comment]
No. Did not get one.

**Comment by jmejiaz** [comment]
This looks like a real  problem. And seems there is not a solution yet.

**Comment by regnete** [comment]
Hi guys! I'm missing relevant info on how to reproduce this. e.g: Which Android version are we talking about?
