### ISSUE TITLE
Document Viewer not loading PDF Document on initial load – Windows 10*

### ISSUE THREAD

**Issue by ChinniKrishna12** [sitewaerts/cordova-plugin-document-viewer#114]
Hi Team, 
I am trying to apply Document Viewer plugin in my cordova application, Facing an issue while loading the PDF document to display on click of a button.

Please find the attachments which refers what I mean.

NOTE: Came across an console error while loading the PDF document on click of a button saying “ Unknown directive 'child-src' in <meta http-equiv="Content-Security-Policy"> - directive will be ignored.” 

PDF file has loaded in the viewer and display on click of “ LAYOUT BUTTON which is besides File name display in PDF Viewer.   PDF document displaying only on click of those button(layout buttons on the Viewer) on the top besides file name.

Could you please guide me on this. Really appreciate  your help.
![consoleissue](https://user-images.githubusercontent.com/20668229/41736380-44d3d92c-755a-11e8-9e9f-96be9393eed1.png)
![git hub plugin issue](https://user-images.githubusercontent.com/20668229/41736381-44e462a6-755a-11e8-855a-26b1acc93e94.png)

**Comment by regnete** [comment]
Could be caused by css issues as the viewer is not fullscreen sized.  And what about the vertical scrollbar? Looks like you are trying to change the viewer layout with some css hacks. may be these hack destroy the layout.

**Comment by regnete** [comment]
- may be your projects css is somehow interfering the viewers css
- may be you are using an outdated version of the plugin via ionic
- we do not support ionic
- windows 8.1 is not supported anymore bx the recent version of the plugin
- use a debugger to find out whats going wrong

**Comment by ChinniKrishna12** [comment]
@regnete Thanks for your replay. It's not because of css issue but it's looks like plugin display PDF's in Document viewer only when while using latest version browser ( Especially EDGE ).

**Comment by regnete** [comment]
Browser? The plugin supports ios, android and windows10 apps. Browsers are not supported.
