### ISSUE TITLE
Sudden weird issue - only view document once

### ISSUE THREAD

**Issue by johnkochjr** [sitewaerts/cordova-plugin-document-viewer#115]
This week, out of nowhere, we started getting a weird issue. We haven't changed anything on this app that has been out for 9 months but here is the issue.

Install the app, go to view a document (We download the document to local and then open to view) and we can see the document just fine. Back out back to the menu and attempt to view the same file and now we get an error.  This: 

We are removing the file after the documentviewer is closed. Like I said, this has been working so... what changed?

Error in SitewaertsDocumentViewer.viewDocument():
[object Object]
[16:50:32]  console.error: Document viewer error { "status": 9, "message": "mkdirs
            /data/user/0/com.trshealthcare.trsnurse/cache/tmp/DocumentViewerPlugin failed.", "details":
            "org.json.JSONException: mkdirs /data/user/0/com.trshealthcare.trsnurse/cache/tmp/DocumentViewerPlugin
            failed.\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.getAccessibleFileNew(DocumentViewerPlugin.java:750)\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.getAccessibleFile(DocumentViewerPlugin.java:706)\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin._open(DocumentViewerPlugin.java:487)\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.doExecute(DocumentViewerPlugin.java:312)\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.access$000(DocumentViewerPlugin.java:49)\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin$1.run(DocumentViewerPlugin.java:185)\n\tat
            java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat
            java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat
            java.lang.Thread.run(Thread.java:818)\nCaused by: java.io.IOException: mkdirs
            /data/user/0/com.trshealthcare.trsnurse/cache/tmp/DocumentViewerPlugin failed.\n\tat
            de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.getAccessibleFileNew(DocumentViewerPlugin.java:736)\n\t...
            8 more\n" }

**Comment by regnete** [comment]
As you didn't create a new release of your app, there are no changes in the plugins code either.
So the issue must have been there since you released your app or the issue is caused by an android software update.

The issue ocours when the plugin tries to create a plgin specific temp-dir as copy location for the pdf you are trying to view. (https://github.com/sitewaerts/cordova-plugin-document-viewer/blob/master/src/android/de/sitewaerts/cordova/documentviewer/DocumentViewerPlugin.java#L734)
As the code performs a check if the dir already exists before it tries to create it, I guess there must be either a concurrency issue (which is not realy a realistic option) or the issue is file permission indicated.

- Are you able to reproduce the issue with the sample app?
- Which andoid SDK version / api level are you targeting when building your app?
- Does the issue disapear when you create a new release of your app targeting a newer android api level?
- What is the location/path of the document you are trying to show?
- What ist the path you delete after the document has been shown?
- Does the isue appear on devices running specific android versions only or on any android version?
- There may be issues running the plugin in device emulators. Does the issue occur on physical devices?

**Comment by johnkochjr** [comment]
well, regardless of when it stopped working, I need to figure out what is going on. I am creating a path:
this.file.dataDirectory and then adding file name. onClose I remove the same file. I have verified that the file is created and removed. 

When I view it again, the error thrown is when it is creating a temp file in the tmp/cache (or cache/tmp I don't recall) ... I don't know how to access that file and remove it or even if I should. The issue appears on every device we have tried. 

I think it is currently set to api level 24

does any of that help?

**Comment by johnkochjr** [comment]
Also I am using:
"cordova-plugin-document-viewer": {
            "version": "0.9.6",
            "resolved": "https://registry.npmjs.org/cordova-plugin-document-viewer/-/cordova-plugin-document-viewer-0.9.6.tgz",
            "integrity": "sha1-z/efQZJmheBCe0wlY4jeyNoufCg="
        },

**Comment by johnkochjr** [comment]
cordova-plugin-document-viewer     0.9.10
@ionic-native/document-viewer      4.9.0

**Comment by johnkochjr** [comment]
If it helps - here is the entire code being used:

import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, AlertController, LoadingController, Refresher, ActionSheetController, Platform } from 'ionic-angular';
import {
  AssignmentsService, IContract, ISubmission,
  TimesheetService, ITimesheetListItem, ConnectionService,
  AuthService,
  AppSettingsService,
  ITimesheet
} from '../../providers';
import { TrsBasePage } from '../';
import { DocumentViewer, DocumentViewerOptions } from '@ionic-native/document-viewer';
import { FileTransfer, FileTransferObject, FileUploadOptions } from '@ionic-native/file-transfer';
import { File, FileEntry } from '@ionic-native/file';
import { Camera, CameraOptions } from '@ionic-native/camera';

@IonicPage()
@Component({
  selector: 'page-assignments',
  templateUrl: 'assignments.html',
})
export class AssignmentsPage extends TrsBasePage {

  private _hideMenuToggle: boolean = false;
  public get hideMenuToggle(): boolean {
    return this._hideMenuToggle;
  }

  private _dataLoaded: boolean = false;
  public get dataLoaded(): boolean {
    return this.assignmentsService.currentAssignments.length > 0 || this._dataLoaded;
  }

  constructor(public navCtrl: NavController, public navParams: NavParams,
    private assignmentsService: AssignmentsService,
    alertCtrl: AlertController,
    loadingCtrl: LoadingController,
    private authService: AuthService,
    private appSettingsService: AppSettingsService,
    private timesheetService: TimesheetService,
    private connectionService: ConnectionService,
    private actionSheetController: ActionSheetController,
    private documentViewer: DocumentViewer,
    private fileTransfer: FileTransfer,
    private file: File,
    private platform: Platform,
    private camera: Camera) {
    super(loadingCtrl, alertCtrl);

    // this.navCtrl.viewWillEnter.subscribe(i => {
    //   try {
    //     this.handleTimesheetClosed();
    //   } catch (error) {
    //     this.dismissLoading();
    //     this.log(error);
    //   };
    // });
  }

  private log(message: string, data?: any) {
    if (data != undefined)
      console.log(`ASSIGNMENTS-COMPONENT: ${message}`, data);
    else
      console.log(`ASSIGNMENTS-COMPONENT: ${message}`);
  }

  showAssignment(contract: IContract) {
    this.navCtrl.push('AssignmentDetailPage', { contractId: contract.contractId, contract: contract })
  }

  showOffer(submission: ISubmission) {
    this.navCtrl.push('OfferPage', { submission })
  }

  getContractImageUrl(contract: IContract) {
    return `url(${contract.location.photoUrl})`;
  }

  get assignmentHeaderHeight(): string {
    return `${(window.innerWidth * .5625)}px`;
  }

  private _loadingTimesheets: Boolean = false;
  get loadingTimesheets(): Boolean {
    return this._loadingTimesheets;
  }

  showTimesheetDetail(timesheetId: number) {
    if (!this.connectionService.hasConnection) {
      this.timesheetService.isTimesheetCached(timesheetId.toString()).then(isCached => {
        if (!isCached) {
          this.trsAlerts.showTimesheetUnavailableOffline();
        } else {
          this.timesheetService.clearLastTimesheetClosed();
          this.navCtrl.push('TimesheetDetailPage', { timesheetId }).then(() => {
            console.log('FIRED');
          });
        }
      })
    } else {
      this.timesheetService.clearLastTimesheetClosed();
      this.navCtrl.push('TimesheetDetailPage', { timesheetId }).then(() => {
        console.log('FIRED');
      });

    }
  }

  // private handleTimesheetClosed() {
  //   this.log('Checking timesheet closed');
  //   if (this.timesheetService && this.timesheetService.lastTimesheetClosed) {
  //     this.log('Last timesheet was closed, refreshing');
  //     this.timesheetService.clearLastTimesheetClosed();
  //     this.load(null, true);
  //   }
  // }

  public load(refresher: Refresher = null, force = false) {
    this.assignmentsService.load(!!refresher || force)
      .then((result: boolean) => {
        this._dataLoaded = true;
        this.checkStatusProgress();
        if (refresher) {
          refresher.complete();
        }

      },
        this.apiErrorHandler.bind(this)
      );
  }

  aquirePhoto(sourceType: number): Promise<string> {
    const options: CameraOptions = {
      sourceType,
      quality: 100,
      targetHeight: 2048,
      targetWidth: 1582,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
    }

    return this.camera.getPicture(options).then((filePath) => {
      return Promise.resolve(filePath);
    });
  }

  uploadTimesheet(filePath: string, urlPath): Promise<any> {
    const fileTransfer: FileTransferObject = this.fileTransfer.create();
    var requestOptions = this.appSettingsService.getHttpRequestOptions(this.authService);

    let options: FileUploadOptions = {
      fileKey: 'file',
      fileName: 'profile-photo.jpg',
      headers: requestOptions.headers,
      httpMethod: 'POST'
    }

    this.showLoading("Uploading Timesheet");

    return fileTransfer.upload(filePath, this.appSettingsService.getApiUrl(urlPath), options)
      .then((data) => {
        return this.dismissLoading().then(() => this.load(null, true))
      })
      .catch(error => {
        this.dismissLoading();
        return Promise.reject(error);
      })
  }

  // showPdfTimesheetAndroid(timesheetId: string, urlPath: string): Promise<any> {
  //   this.log("Android timesheet show");
  //   let path = `${this.file.externalDataDirectory}${timesheetId}.pdf`;

  // }

  showPdfTimesheet(timesheetId: string, urlPath: string): Promise<any> {
    this.log('Showing pdf timesheet2');

    let path = `${this.file.dataDirectory}${timesheetId}.pdf`;
    let assetPath = `assets/${timesheetId}.pdf`;
    const options: DocumentViewerOptions = {
      title: 'Timesheet',
      email: { enabled: true },
      print: { enabled: true },
      openWith: { enabled: true }
    }

    let onShow = () => {
      this.log('Document Show');
    };
    let onClose = () => {
      this.log('Document Close, removing temporary document');
      try {
        this.file.removeFile(this.file.dataDirectory, `${timesheetId}.pdf`);
        this.log(`Document cleanup of ${path} successful`);
      } catch (error) {
        this.log(`Document cleanup failed: ${path} : ERROR: ${error.message}`);
      }
    };

    let onMissingApp = (appId, installer) => {

      let confirm = this.alertCtrl.create({
        title: 'PDF Viewer Unavailable',
        message: 'In order to view and print your timesheet, a document viewer will need to be installed. Would you like to install this free viewer now?',
        buttons: [
          {
            text: 'No',
            handler: () => {
            }
          },
          {
            text: 'Yes',
            handler: installer
          }
        ]
      });
      confirm.present();

      this.log('Application Missing', appId);
    };

    let onError = (error) => {
      this.showError("Unable to Show Timesheet", error.message);
      console.error('Document viewer error', JSON.stringify(error, null, 4));
    };

    if ('cordova' in window) {
      this.platform.ready().then(() => {
        this.log('cordova available');
        this.showLoading();
        let transferObject = this.fileTransfer.create();
        let headers = {
          Authorization: this.appSettingsService.getHttpRequestOptions(this.authService).headers.get('Authorization')
        };
        return transferObject.download(
          this.appSettingsService.getApiUrl(urlPath),
          path, true, { headers },
        ).then((fileEntry: FileEntry) => {
          this.dismissLoading();

          this.log(`Opening file ${path}`);
          try {
            this.documentViewer.viewDocument(path, 'application/pdf', options, onShow, onClose, onMissingApp, onError);
            return
          }
          catch (error) {
            this.log(error)
          }
        })
          .catch(err => {
            this.dismissLoading();
            return Promise.reject(err);
          });
      });
    } else {
      return Promise.reject('File preview capabilities are only available on a device.');
    }
  }

  startFileWorkflow(timesheet: ITimesheetListItem) {
    const buttons: Array<any> = [
      {
        text: 'View Timesheet',
        icon: !this.platform.is('ios') ? 'cloud-download' : null,
        handler: () => {
          if (!('cordova' in window)) {
            return;
          }
          let urlPath = `/timesheet/viewTimesheetAttachment/${timesheet.generatedDocVerId}`;
          //let urlPath = `timesheet/viewTimesheetReport/${timesheet.timesheetId}`;


          this.showPdfTimesheet(timesheet.timesheetId, urlPath)
            .catch(this.apiErrorHandler.bind(this))
        }
      }
    ];

    if (timesheet.uploadSignedVisible) {
      buttons.push({
        text: 'Take a Picture',
        icon: !this.platform.is('ios') ? 'cloud-upload' : null,
        handler: () => {
          if (!('cordova' in window)) {
            return;
          }

          let urlPath = `/timesheet/UploadPdfTimesheet/${timesheet.timesheetId}`;

          return this.aquirePhoto(1)
            .then(filePath => {
              return this.uploadTimesheet(filePath, urlPath);
            })
            .then(() => this.load(null, true))
            .catch(
              err => {
                this.dismissLoading();
                this.log('File upload errored', JSON.stringify(err));
                this.apiErrorHandler(err);
              }
            )
        }
      });

      buttons.push({
        text: 'Upload Signed Timesheet',
        icon: !this.platform.is('ios') ? 'cloud-upload' : null,
        handler: () => {
          if (!('cordova' in window)) {
            return;
          }

          let urlPath = `/timesheet/UploadPdfTimesheet/${timesheet.timesheetId}`;

          return this.aquirePhoto(0)
            .then(filePath => {
              return this.uploadTimesheet(filePath, urlPath);
            })
            .then(() => this.load(null, true))
            .catch(
              err => {
                this.dismissLoading();
                this.log('File upload errored', JSON.stringify(err));
                this.apiErrorHandler(err);
              }
            )
        }
      });
    }

    if (timesheet.viewSignedVisible) {
      buttons.push({
        text: 'Download Signed Timesheet',
        icon: !this.platform.is('ios') ? 'folder' : null,
        handler: () => {
          if (!('cordova' in window)) {
            return;
          }

          let urlPath = `/timesheet/viewTimesheetAttachment/${timesheet.documentVersionId}`;
          this.showPdfTimesheet(timesheet.timesheetId, urlPath)
            .catch(this.apiErrorHandler.bind(this))
        }
      });
    }

    buttons.push({
      text: 'Cancel',
      role: 'cancel',
      icon: !this.platform.is('ios') ? 'close' : null,
      handler: () => {
        // Nothing needed
      }
    });

    let actionSheet = this.actionSheetController.create({
      title: 'Signed Timesheet Actions',
      cssClass: 'action-sheets-basic-page',
      buttons: buttons
    });

    return actionSheet.present();
  }

  checkStatusProgress() {
    this.log("CHecking for processing status");
    let assCount = this.assignmentsService.currentAssignments.filter((assignment: IContract) => {
      return assignment.timesheets.filter((item: ITimesheetListItem) => {
        if (item.status == "Processing") this.log("Found PROCESSING");
        return item.status == "Processing";
      }).length > 0;
    }).length;

    this._reloadTimesheets = assCount > 0;
    if (this._reloadTimesheets) {
      this.checkTimesheetStatus();
    } else {
      this.log("All clear on status");
    }
    return this._reloadTimesheets;
  }
  checkTimesheetStatus() {
    this.log("Setting status check timer");
    setTimeout(() => {
      //LOAD TIMESHEETS
      this.log("CHecking for status update");
      this.assignmentsService.load(true)
        .then((result: boolean) => {
          if (this.checkStatusProgress()) {
            this.log("Not finished. Set recheck");
            this.checkTimesheetStatus();
          } else {
            this.log("All clear - status should be set");
            this._dataLoaded = true;
          }
        },
          this.apiErrorHandler.bind(this)
        );
    }, 15000);
  }
  getStatusClass(timesheet: ITimesheetListItem) {
    return `status-${(timesheet.status || 'unknown').toLowerCase().replace(/[\s]/g, '-')}`
  }
  gotoLink(url) {
    window.open(url, '_system');
  }
  _reloadTimesheets: boolean;

  ngOnInit() {
    this._hideMenuToggle = !!this.navParams.data.hideMenuToggle;
    if (this.assignmentsService.currentAssignments.length > 0) {
      this._dataLoaded = true;
      this.checkStatusProgress();
    } else {
      this.load();
    }
  }
}

**Comment by johnkochjr** [comment]
Found the issue: I was removing the file I downloaded but it looks as though CleverDox takes that file and creates a new one in the tmp directory of the cache directory... so... before loading a file, I just remove all the files and the tmp directory.

this.file.removeRecursively(this.file.cacheDirectory, 'tmp')
    .then(()=>{
      this.log("Removed Directory");
    })
    .catch((error)=>{
      this.log("Error rem dir", error.message);
    })
