### ISSUE TITLE
not work to me to

### ISSUE THREAD

**Issue by alaahwanas** [sitewaerts/cordova-plugin-document-viewer#118]
<head>
  <script type="text/javascript" charset="utf-8" src="cordova.js"></script>

  <script>
    function onDeviceReady() {
      alert('123')
    }

    document.addEventListener("deviceready", onDeviceReady, false);
  </script>

</head>
<ion-buttons text-center>
          <button ion-button color="light" clear (click)="openKeraa()">  قرائتي </button>
        </ion-buttons>

and her is my ts file

  openKeraa() {
    const options: DocumentViewerOptions = {
      title: 'My PDF'
    }

    this.document.viewDocument('assets/test.pdf', 'application/pdf', options)

  }

**Comment by lim-enhui** [comment]
there is an issue with this. hope the contributor can fix this.. the muReader does not support current android version in my emulator also... and older platform of android versions... we are stuck
