### ISSUE TITLE
Question: hyperlink

### ISSUE THREAD

**Issue by njtaz76** [sitewaerts/cordova-plugin-document-viewer#12]
Love this plugin and works awesome. Am I missing something to enable hyperlinks or is that not implemented?  Thank you!

**Comment by regnete** [comment]
hyperlinks are not yet supported.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 04.08.2015 um 04:34 schrieb njtaz76 <notifications@github.com<mailto:notifications@github.com>>:


Love this plugin and works awesome. Am I missing something to enable hyperlinks or is that not implemented? Thank you!

**Comment by njtaz76** [comment]
Alright.  Thank you for reply.  Is there any time line?

**Comment by regnete** [comment]
No. If you want to implement a new feature, you are welcome!

Von: njtaz76 [mailto:notifications@github.com]
Gesendet: Dienstag, 4. August 2015 13:50
An: sitewaerts/cordova-plugin-document-viewer
Cc: Felix Schauerte
Betreff: Re: [cordova-plugin-document-viewer] Question: hyperlink (#12)

Alright. Thank you for reply. Is there any time line?
On Aug 4, 2015 1:18 AM, "Felix Schauerte" <notifications@github.com<mailto:notifications@github.com>> wrote:

> hyperlinks are not yet supported.
>
>
> Felix Schauerte
> sitewaerts GmbH
> www.sitewaerts.de<http://www.sitewaerts.de<http://www.sitewaerts.de%3chttp:/www.sitewaerts.de>>
>
> Am 04.08.2015 um 04:34 schrieb njtaz76 <notifications@github.com<mailto:
<mailto:notifications@github.com%3cmailto:%0b>> notifications@github.com<mailto:notifications@github.com>>>:

**Comment by regnete** [comment]
Hyperlinks are supported in the iOS viewer. We are not planing to support links on Android or Windows due to technical limitations.
