### ISSUE TITLE
How to use cordova-plugin-document-viewer in Ionic 3 application ?

### ISSUE THREAD

**Issue by abodje** [sitewaerts/cordova-plugin-document-viewer#120]
Hello, I added Cordova Document Viewer Plugin in my ionic application for the installation I made cordova plugin add cordova-plugin-document-viewer and I can not initialize it in my components
Thank you for your help

**Comment by gdvsbp** [comment]
@abodje These are the steps I followed in my Ionic project and it worked just fine: https://ionicacademy.com/pdf-files-ionic/
