### ISSUE TITLE
THE PDF VIEWER FOR IOS HAS BEEN DEPRECATED

### ISSUE THREAD

**Issue by gdvsbp** [sitewaerts/cordova-plugin-document-viewer#122]
The PDF viewer this project uses on iOS, [VFReader](https://github.com/vfr/Reader), has been deprecated by the project owner. They have replaced it with a new version: [UXReader](https://github.com/vfr/UXReader-iOS)

VFReader, which this project uses, does not support the iPhone X. It also does not have retina button images, in case that's the sort of thing your client cares about.

Please update this project to use UX Reader for iOS PDF viewing. At the very least please add a warning to your readme letting potential users know about this issue before they take the time to integrate.

**Comment by alex-steinberg** [comment]
I am using this plugin and it's working on the iPhone X.
