### ISSUE TITLE
ask for download cleverdox viewer

### ISSUE THREAD

**Issue by ECankit** [sitewaerts/cordova-plugin-document-viewer#126]
i follow the ionic https://ionicframework.com/docs/native/document-viewer/ 
steps but after adding this its redirects me to play store for download the cleverdox viewer 
is there any way to direct open the pdf file in local path?
i have also tried ng2-pdf-viewer but its take to much time to load pdf as it convert whole file into Blob type

can anyone help?
thanks in advance

**Comment by rodrigograca31** [comment]
I'm trying to use this other plugin but having a few problems....
https://ionicframework.com/docs/native/file-opener/

**Comment by ECankit** [comment]
> I'm trying to use this other plugin but having a few problems....
> https://ionicframework.com/docs/native/file-opener/

thank you ..
this working fine without any error...

**Comment by Houdhey** [comment]
> > I'm trying to use this other plugin but having a few problems....
> > https://ionicframework.com/docs/native/file-opener/
> 
> thank you ..
> this working fine without any error...

Hello, can you tell me how you did that?

**Comment by ECankit** [comment]
import in app.module.ts file 
import { FileOpener } from '@ionic-native/file-opener';
add it in providers array

in your file import it 
import { FileOpener } from '@ionic-native/file-opener';

make its instance in constructor
constructor(private fileOpener:FileOpener){}

and use like this on open click: 
    this.fileOpener.open('local file path', 'application/pdf')
      .then(() => console.log('File is opened'))
      .catch(e => console.log('Error opening file', e));

my ionic app versions are as below;
Ionic:

   ionic (Ionic CLI) : 4.2.1

System:

   NodeJS : v12.13.1
   npm    : 6.9.0
   OS     : Windows 10
