### ISSUE TITLE
Supported Document Types

### ISSUE THREAD

**Issue by ChrisTomAlx** [sitewaerts/cordova-plugin-document-viewer#128]
Hey keep up the awesome work.

In the readme you have specified ability to view different document types. I was wondering if there is a full list of supported doc types. 

> Plugin's Purpose
>The purpose of the plugin is to create a platform independent javascript interface for Cordova based mobile applications to view different document types by using native viewer components.

More importantly is excel view supported? If not I would like to help in creating a plugin that does support excel view. If you could point me in the right direction, that would be incredibly helpful.

**Comment by regnete** [comment]
Currently the only supported type is pdf.
I havent't ever thought about how to implement a excel viewer. But may you should have a look at google to find out if there is a javascript based excel viewer which you could then integrate into the plugin. 
That would be a great extension!

**Comment by ChrisTomAlx** [comment]
@regnete Thanks for your quick reply. I will look into it!!

**Comment by merbin2012** [comment]
.pdf also ask me to download other application.
