### ISSUE TITLE
Some vector icons was not displayed in pdf

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sitewaerts/cordova-plugin-document-viewer#129]
Hallo @regnete!

Any idea why?

![image](https://user-images.githubusercontent.com/2271337/51328017-c0844a80-1a72-11e9-8f7f-3bd42488f34b.png)

**Comment by WuglyakBolgoink** [comment]
up..

**Comment by WuglyakBolgoink** [comment]
Hallo @regnete / @Enrico204 

can you please check this? I have this issue since 17.12.2018... 

If this plugin has no more potential or maintainers , can you give me any other alternatives for PDF viewer on cordova apps?

**Comment by Enrico204** [comment]
Uhm, the iOS backend needs a complete rewrite over `PDFKit` as the current backend is deprecated. Meanwhile, can you provide a sample PDF that triggers this behavior? Which platform is affected?

**Comment by regnete** [comment]
Sadly we decided to put no more work in this plugin. For our own puposes we want to switch over to a pure javascript impl based on pdfjs.

**Comment by regnete** [comment]
@Enrico204: Are you willing to continue with this plugin?

**Comment by Enrico204** [comment]
To be honest, I don't have so much time to invest in development in these days. And I think that PDF.js is mature enough to be a good replacement.

Maybe we should officially archive the plugin and indicate an upgrade path towards PDF.js or some alternatives. I have an app where I can do some experiments and create some documentation about this migration process (it might take a while). What do you think about this?

**Comment by regnete** [comment]
I am already working on an alternative solution basedn on pdfjs. But I haven't yet decided wether it will be published for free and if it will be a simple javascript library or a cordova plugin.

I have put an "archived" notice in the README. Your additions are welcome!
