### ISSUE TITLE
Previous document pages displayed after opening new document

### ISSUE THREAD

**Issue by joevernonintegritie** [sitewaerts/cordova-plugin-document-viewer#13]
On iOS devices, after opening 1 document and closing it and then opening a different document the previous documents pages are displayed briefly before the plugin loads the new document.

In addition the preview pages at the bottom display the previous document loaded and not the current document. Have tried on both android and iOS and it only seems to be happening on iOS. 

Great work BTW!

**Comment by regnete** [comment]
Sorry, I haven't had any time to work on the plugin. Is this issue still relevant with the current iOS release?

**Comment by kevin-sharktek** [comment]
Yes this issue is still present on iOS 9.

**Comment by regnete** [comment]
Is this issue still relevant on iOS 10? We cannot reproduce the described behaviour.

Waht do you exactly mean with 'a different document'? 
A: Calling the viewer with a different file url
B: Modifying the file and then calling the viewer with an unchanged file url.

In case B there could be caching issues. Try to call the viewer always with a new/changed file url.

**Comment by regnete** [comment]
seems to be solved
