### ISSUE TITLE
Print is not enabled

### ISSUE THREAD

**Issue by selmo47** [sitewaerts/cordova-plugin-document-viewer#131]
I cannot see a "Print" button on the viewer
In android 6.0

I have the following code:
`const options: DocumentViewerOptions = {
      print: { enabled: true}
};
const PDF = "application/pdf";
this.document.viewDocument('path/to/file.pdf', PDF, options);
`

The document is opend correctly in browser

the "email" and "openWith" work well, but not the print

**Comment by regnete** [comment]
Did you try `{print: { enabled: true } }` ?

**Comment by selmo47** [comment]
Hi @regnete , it was an a typo in the issue raising (I have edited the post)

Its `print: {enabled: true}` in my code, but the print button dosent appear
