### ISSUE TITLE
Change cleverdox viewer

### ISSUE THREAD

**Issue by uldcra** [sitewaerts/cordova-plugin-document-viewer#136]
Hello Everybody.

There are anything possibilty change cleverboxview for another pdfviewer, because the new version of android not support this app.
 
thanks

**Comment by regnete** [comment]
you could play arround with two undocumented options:

```
options.android.viewerAppPackage = 'de.sitewaerts.cleverdox.viewer';
options.android.viewerAppActivity = 'DocumentViewerActivity';
```

**Comment by uldcra** [comment]
Thanks regnete.
Sorry for the big delay.
