### ISSUE TITLE
GrandUriPersmission in AndroidManifest.xml

### ISSUE THREAD

**Issue by maltorpro** [sitewaerts/cordova-plugin-document-viewer#137]
The plugin sets the provider "de.sitewaerts.cordova.documentviewer.FileProvider" with the grandUriPermission="true" in the AndroidManifest.xml.
According to google developer documentation https://developer.android.com/guide/topics/manifest/provider-element#gprmsn the given permission must be revoked via the function Context.revokeUriPermission().
Is it possible to remove the entry and use grantUriPermission before using the FileProvider and after revokeUriPermission in the class "DocumentViewerPlugin"?

**Comment by regnete** [comment]
please proivide a pull request as I am currenly under heavy work load.
