### ISSUE TITLE
canViewDocument(): "JSON error""

### ISSUE THREAD

**Issue by mohammadebrahim** [sitewaerts/cordova-plugin-document-viewer#14]
[INFO:CONSOLE(196)] "Error in SitewaertsDocumentViewer.canViewDocument(): "JSON error"", source: file:///android_asset/www/plugins/de.sitewaerts.cordova.documentviewer/www/sitewaertsdocumentviewer.js (196)

**Comment by regnete** [comment]
You obviously passed invalid options to canViewDocument(). Start a debugging session via chrome browser with a breakpoint in line 164 to inspect your function call arguments.

**Comment by naatogmagithub** [comment]
Can somebody show me a quick working example of valid arguments that should be passed to the canViewDocument();

**Comment by regnete** [comment]
https://github.com/sitewaerts/cordova-plugin-document-viewer-sample-app/blob/master/www/js/common.js#L325
