### ISSUE TITLE
XCode < 11 compatibility broken in 0.9.12

### ISSUE THREAD

**Issue by Enrico204** [sitewaerts/cordova-plugin-document-viewer#142]
With the last update (0.9.12) the package is not compiling with XCode 10 (and maybe in previous versions) due to missing property `windowScene` (see below) in previous iOS SDKs. I suggest either to add compatibility with older XCode, or add an informative note in the README regarding the compatibility.

The error:
```
[zap]/platforms/ios/MyApp/Plugins/cordova-plugin-document-viewer/SDVReaderViewController.m:1133:94: error: property 'windowScene' not found on object of type 'UIWindow *'
        statusBar = [[UIView alloc]initWithFrame:[UIApplication sharedApplication].keyWindow.windowScene.statusBarManager.statusBarFrame];
```

I think that it's related to #141

**Comment by regnete** [comment]
anybody out there to fix this? I guess we need some kind of compiler instruction to keep the code compatible with old and current versions of xcode, but I dont' have any knowledge on how to do this in C code.

**Comment by Enrico204** [comment]
I think it's something like:
```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_13_0
    // SDK for iOS 13 available (XCode 11 supports SDK 13)
#else
    // SDK for iOS 13 not available (XCode 10 or older)
#endif
```

These are pragmas, so no indentation is needed AFAIK (in plain C it's not working with indentation). In the first code block you can fill the current code, in the second you can restore the previous behavior (eg. before #141)

**Comment by Enrico204** [comment]
I created a PR for this #143 , but unfortunately I can't test it now. I will in few hours/days if no one can test it before that

**Comment by Enrico204** [comment]
I tested with XCode 10 and it's compiling with the last (second) commit that I made in the PR

**Comment by regnete** [comment]
see v0.9.13
Thx a lot!
