### ISSUE TITLE
ios Error

### ISSUE THREAD

**Issue by ChokeBilly** [sitewaerts/cordova-plugin-document-viewer#144]
Error:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'

Code:

assert(document != nil); // Must have a valid ReaderDocument    
    self.view.backgroundColor = [UIColor grayColor]; // Neutral gray
    UIView *statusBar = [[[UIApplication sharedApplication] valueForKey:@"statusBarWindow"] valueForKey:@"statusBar"];

**Comment by regnete** [comment]
which is the version of the plugin you are using?
