### ISSUE TITLE
No longer opening on Android

### ISSUE THREAD

**Issue by batesy87** [sitewaerts/cordova-plugin-document-viewer#146]
When trying ViewDocument()

file:///data/user/0/com.my.app/files/filename.pdf

Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

Android 8.1
target SDK 28
cordova android 8.1.0
cordova-plugin-document-viewer: 0.9.13

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
W/System.err:     at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
W/System.err:     at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
W/System.err:     at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin._open(DocumentViewerPlugin.java:500)
W/System.err:     at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.doExecute(DocumentViewerPlugin.java:311)
W/System.err:     at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin.access$000(DocumentViewerPlugin.java:49)
W/System.err:     at de.sitewaerts.cordova.documentviewer.DocumentViewerPlugin$1.run(DocumentViewerPlugin.java:184)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by batesy87** [comment]
#147 Seems to fix this issue

**Comment by nhhockeyplayer** [comment]
no pdfs on android yet... show stopper for cordova document-viewer

Im seeing this on the following



Ionic:

   Ionic CLI                     : 5.4.15 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.803.23
   @angular-devkit/schematics    : 8.3.23
   @angular/cli                  : 8.3.23
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   ios-sim : 8.0.2
   NodeJS  : v13.6.0 (/usr/local/bin/node)
   npm     : 6.13.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.3.1 Build version 11C504

**Comment by aexei** [comment]
@batesy87: Thx! Works great :)

**Comment by JMente** [comment]
cleverdox stop working on Android 11 and up
