### ISSUE TITLE
why should I install cleverdox Viewer?

### ISSUE THREAD

**Issue by kotran88** [sitewaerts/cordova-plugin-document-viewer#150]
isn't it possible to use internal pdf viewer  ?

**Comment by ochikov** [comment]
I am also interested in this question. Can I use adobe pdf viewer or other internal viewer?

**Comment by regnete** [comment]
please clarify your question.
the plugin is an internal pdf viewer.
>

**Comment by ochikov** [comment]
> please clarify your question. the plugin is an internal pdf viewer.
> […](#)
When I tried to open a pdf, it points me to the store and asks me to install cleverdox app. Can't I preview the pdf with already installed apps for PDFs ?

**Comment by regnete** [comment]
so we are talking about android os.
> 
read the docs:

on android we cannot embed the viewer due to license restrictions.

common pdf viewers do not restrict your users to viewing but also allow save, print, share etc.

**Comment by regnete** [comment]
are your questions answered now? may I close the issue?
