### ISSUE TITLE
Cannot build on Android

### ISSUE THREAD

**Issue by jameshhood** [sitewaerts/cordova-plugin-document-viewer#153]
I have my cordova project with a clean android platform install. Build and run my project and it works just fine. The moment that I add this plugin, android will no longer compile due to AndroidX dependencies and problems with android.support.v4.

Is there a work around or something I can do to get this to build? I've read other issues about it just not being able to open PDFs but I'm not able to even compile my android project

`
> Task :app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.appcompat:appcompat:1.0.0, androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.core:core:1.0.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.print:print:1.0.0
`

I've tried setting the AndroidX property to true and it just goes further down the support.v4 dependency rabbit hole. Before I added this plugin, I hadn't needed to change anything manually about my android cordova app at all. Something seems jacked up here.

**Comment by regnete** [comment]
We are using the plugin with the following settings im config.xml:
```xml
<preference name="android-minSdkVersion" value="22"/>
<preference name="android-targetSdkVersion" value="29"/>
<preference name="AndroidXEnabled" value="true" />
```

The following plugins (beside others obviously not related to this issue) are contained in our apps:
```
cordova-plugin-androidx-adapter
cordova-android-support-gradle-release
```

We are currently using cordova ```android@8.0.0``` to build out apps.
