### ISSUE TITLE
Error in SitewaertsDocumentViewer.viewDocument():  [object Object]

### ISSUE THREAD

**Issue by Chamthi** [sitewaerts/cordova-plugin-document-viewer#155]
can't we pass parameters this way ?
```
const options: DocumentViewerOptions = {
        title: 'My PDF'
      }
 this.documentViewer.viewDocument(img.file, 'application/pdf', options);
```

pdf file have been assigned to img.file property 

`Msg: Error in SitewaertsDocumentViewer.viewDocument():  [object Object]`

How can i fix this?

**Comment by regnete** [comment]
Use a javascript debugger to find out whats going on.
