### ISSUE TITLE
iphone 12/iOS 14.7.1 - PDF not showed

### ISSUE THREAD

**Issue by sejcjan** [sitewaerts/cordova-plugin-document-viewer#158]
On iPhone 12 is PDF not showed. It is work on Android and older versions of iPhones. Also iPad works.
Can be related to higher resolution and scaling on iPhone 12? Here is no error message (we do not got any).

![2021-09-13 16 06 16](https://user-images.githubusercontent.com/90177898/133098366-297a8e51-0647-44b8-af0c-8a6df3e90e75.jpg)

**Comment by regnete** [comment]
!!! This plugin is no longer maintained. For a cross platform pdf viewer take a look at pdf.js !!!

**Comment by sejcjan** [comment]
> 
> 
> !!! This plugin is no longer maintained. For a cross platform pdf viewer take a look at pdf.js !!!

thank you for information! I missed that, you mentioned pdf.js (https://github.com/mozilla/pdf.js) and for web/ios prebuild https://github.com/mozilla/pdfjs-dist ? Thank you!
