### ISSUE TITLE
The plugin now tries to open pdf on muPDF and fails on Android .

### ISSUE THREAD

**Issue by abhilashkgeorge** [sitewaerts/cordova-plugin-document-viewer#159]
The app url https://play.google.com/store/apps/details?id=de.sitewaerts.cleverdox.viewer doesn't exist.

**Readme reference**
Android
Due to license restrictions in muPDF, the plugin dispatches to a separate (free) viewer app based on muPDF. If the viewer app is not yet installed, the user may be redirected to the google play app store.

https://play.google.com/store/apps/details?id=de.sitewaerts.cleverdox.viewer

https://github.com/sitewaerts/android-document-viewer

<img width="866" alt="image" src="https://github.com/sitewaerts/cordova-plugin-document-viewer/assets/72414977/d01265ce-04ce-4c6a-8fbc-32c9a66dcba3">

Any fixes?

**Comment by regnete** [comment]
This plugin is no longer supported.
