### ISSUE TITLE
No viewer for application/pdf error

### ISSUE THREAD

**Issue by efanurag** [sitewaerts/cordova-plugin-document-viewer#16]
Getting error in iOS "Error in SitewaertsDocumentViewer.viewDocument(): No viewer for application/pdf" while opening a pdf file.

Here is my code:
SitewaertsDocumentViewer.viewDocument(cordova.file.applicationDirectory + "assets/images/sample.pdf",'application/pdf');

**Comment by regnete** [comment]
the error message is some kind of miss leading. I guess your file uri cannot be resolved to a valid pdf file.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 22.01.2016 um 05:20 schrieb efanurag <notifications@github.com<mailto:notifications@github.com>>:


Getting error "Error in SitewaertsDocumentViewerviewDocument(): No viewer for application/pdf" while opening a pdf file

Here is my code:
SitewaertsDocumentViewerviewDocument(cordovafileapplicationDirectory + "assets/images/samplepdf",'application/pdf');

-

**Comment by efanurag** [comment]
Thanks. Right the problem was with file uri only and the message was misleading.

I was earlier using "assets/images/sample.pdf" and the right path is "www/assets/images/sample.pdf"

**Comment by yiweicao** [comment]
anything new? I have the same issue on iOS. Either www/assets/ or assets/ does not work.

**Comment by regnete** [comment]
This is not an issue with the plugin. Use absolute urls as stated in the [docs](https://github.com/sitewaerts/cordova-plugin-document-viewer#url).

Have a look at the [cordova docs](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/#where-to-store-files) to find out how to build absolute file urls for your platform and file path.

**Comment by kudeiro** [comment]
it fails with absolute urls too
