### ISSUE TITLE
Documentation is not mentioning the need to install the cleverdox viewer app

### ISSUE THREAD

**Issue by mysegfault** [sitewaerts/cordova-plugin-document-viewer#19]
Hello,

Please write clearly in your README that the user has to install another app on this phone in order to open the PDF files within the app... Because I lost a lot of time trying to integrate this plugin until I realize this.

Thanks.

**Comment by regnete** [comment]
It is stated very clearly in the docs since the beginning of this project: 
https://github.com/sitewaerts/cordova-plugin-document-viewer#android
