### ISSUE TITLE
Disable Navigation view

### ISSUE THREAD

**Issue by warrenbell** [sitewaerts/cordova-plugin-document-viewer#2]
Is there a way to disable navigation view ? With the following options set, there really is no need for this secondary nav view. Should it not be disabled automatically ?

var options = {
                                title: "title",
                                    documentView : {
                                    closeLabel : "Close"
                                },
                                navigationView : {
                                    closeLabel : "Back"
                                },
                                email : {
                                    enabled : false
                                },
                                print : {
                                    enabled : true
                                },
                                openWith : {
                                    enabled : false
                                },
                                bookmarks : {
                                    enabled : false
                                },
                                search : {
                                    enabled : false
                                }
                            };

Thanks,

Warren Bell

**Comment by regnete** [comment]
see #5
