### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by nithincvpoyyil** [sitewaerts/cordova-plugin-document-viewer#21]
Even I enable the option 'search' : true as informed in the documentation, the feature is not there.

**Comment by regnete** [comment]
i will update the docs


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 04.07.2016 um 14:11 schrieb Nithin CV Poyyil <notifications@github.com<mailto:notifications@github.com>>:


Even I enable the option 'search' : true as informed in the documentation, the feature is not there.

-

**Comment by nithincvpoyyil** [comment]
+1

**Comment by andreasekberg83** [comment]
Is this out of date or is it possible to make the search feature work soon? :)

**Comment by regnete** [comment]
Sorry, we are laking capacities to implement this feature. Anybody out there?

**Comment by cyptus** [comment]
as the search-option is still in the docs and the feature does not appear in the app: is this feature available yet?

**Comment by regnete** [comment]
nope
