### ISSUE TITLE
Do not show status bar

### ISSUE THREAD

**Issue by hikaru-shindo** [sitewaerts/cordova-plugin-document-viewer#22]
I disabled the status bar for my app. Now, when the document viewer opens, I get this ugly black placeholder-status-bar without any information in it (since the status bar is disabled).

This should be possible to turn off so it really is a fullscreen view if there is no status bar.

**Comment by regnete** [comment]
Your are free to adapt the implementation to your needs. the source code for iOS and Windows are contained in this git repo. For Android have a look at https://github.com/sitewaerts/android-document-viewer.
