### ISSUE TITLE
Base64 pdf data

### ISSUE THREAD

**Issue by pratikgavas** [sitewaerts/cordova-plugin-document-viewer#26]
In my application, some data is confidential, so I need to encrypt those pdf file into raw data. But How can I show that decrypted raw data in our plugin. Please let me know ASAP.

**Comment by regnete** [comment]
depending on the target os you could implement decryption in native code (C/Java/Javascript). Create a fork and start coding.

A simple base64 encoder cannot provide security for confidential documents. what about password protected pdfs? it is standarised and widly abailable. the plugin lacks support for password protected pdfs, but the os specific code could be easily extended to provide this feature. just go ahead, pull requests are welcome.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 03.10.2016 um 13:39 schrieb pratikgavas <notifications@github.com<mailto:notifications@github.com>>:


In my application, some data is confidential, so I need to encrypt those pdf file into raw data. But How can I show that decrypted raw data in our plugin. Please let me know ASAP.

-

**Comment by regnete** [comment]
decryption could be implemented before the file is apssed to the plugin. integrating proprietary file encryption should not be added to the plugin
