### ISSUE TITLE
Windows - allow document viewer to open on pages other than ones in www/

### ISSUE THREAD

**Issue by svaj** [sitewaerts/cordova-plugin-document-viewer#27]
I ran into an issue where I had a page in /www/<somedir>/index.html that needed to embed the document viewer.  It looks like the inclusion of the iframe was coded to be relative to the current path.  This caused the iframe to fail to load with the following message: APPHOST9613: The application couldn't navigate to"ms-appx-web:///<appname>/www/forms/sitewaertsdocumentviewer/viewer.html because of this error: 80004005.".  I've got a Pull request incoming to address this for windows, I'm not sure if this is also the case for ios or android as I'm currently only using this on a windows device.

**Comment by svaj** [comment]
PR #28

**Comment by regnete** [comment]
pull requested merged. thank you!
