### ISSUE TITLE
'SitewaertsDocumentViewer' is undefined - Windows 10

### ISSUE THREAD

**Issue by ajberry** [sitewaerts/cordova-plugin-document-viewer#30]
Hi, 

I am trying to use this plugin to present PDF documents in my app. The code works fine in Android, but whenever I run the app in Windows, I get the above error. 

Code below for reference: 

SitewaertsDocumentViewer.viewDocument(ret, 'application/pdf', VIEWER_OPTIONS, onShow, onClose, onMissingApp, onError);

ret is a variable I use for the file name (which is checked before the call is made, so nothing wrong with that). 

Full code for page

Gist for code: https://gist.github.com/ajberry/9b13e38bac94981b82d9be46811fa60c

**Comment by regnete** [comment]
Is your code executed after the deviceready event?

https://github.com/sitewaerts/cordova-plugin-document-viewer#plugin-initialization

**Comment by ajberry** [comment]
Yes it is. The code works on Android, but not on Windows 10.

**Comment by regnete** [comment]
we are using the plugin in several windows apps without facing this issue. I don't have a clue whats going wrong in your code.

Do you compile your app explicitly for win10? we always compile for windows81, so that the resulting package is executable on windows 8.1 and windows 10.

may be it works, when compiling for windows8 only. I haven't yet tested the plugin when compiling explicitly for win10.

please use the sample app to reproduce your issue:
https://github.com/sitewaerts/cordova-plugin-document-viewer-sample-app

**Comment by ajberry** [comment]
I'm using the Windows-x86 build in Visual Studio - could it be that causing the issue?

**Comment by regnete** [comment]
May be or not. Try to reproduce your issue with the sample app. I guess you are doing something wrong.

**Comment by ajberry** [comment]
I get the following with the sample app:

The application can't launch the URI at ms-appx://test.pdfviewersampleapp/www/test01.pdf because of this error: -2147024846.

Which is different to the errors I am getting

**Comment by MilindSuryawanshi** [comment]
I can view the pdf in windows 10 cordova app, however my problem is: i want to see the 4/5 page pdf, one by one. Means the view of pdf is single page at a time. as shown in Readme- ios demo screen shots.

**Comment by regnete** [comment]
@MilindSuryawanshi: your comment is of topic. please open a new issue to request a new feauture.

**Comment by MilindSuryawanshi** [comment]
Hello,

I have created a new bug #58.
I have fixed the bug, tested on windows10, requested you to merge the pull
(pull request).
Could you please accept it?.

~Milind

**Comment by regnete** [comment]
Hi,

please do not further spam our corporate email accounts! Use github for github issues.

We obviuosly haven’t had the time to check your pull request. Please respect that, its just an open source project.

You are free to directly use your fork in your own projects which already includes your enhancements. So there is no reason to force us to hurry up.

Felix


Von: Milind [mailto:notifications@github.com]
Gesendet: Montag, 3. April 2017 15:12
An: sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Cc: Felix Schauerte <schauerte@sitewaerts.de>; Comment <comment@noreply.github.com>
Betreff: Re: [sitewaerts/cordova-plugin-document-viewer] 'SitewaertsDocumentViewer' is undefined - Windows 10 (#30)

Hello,

I have created a new bug #58.
I have fixed the bug, tested on windows10, requested you to merge the pull
(pull request).
Could you please accept it?.

~Milind

**Comment by regnete** [comment]
The viewer is now tested with:
- windows 8.1 `<preference name="windows-target-version" value="8.1"/>`
- windows 10 apps (UWP) `<preference name="windows-target-version" value="10.0"/>`

It works as exepected in both environments.

**Comment by Kris824** [comment]
I'm getting the same issue.  cordova.plugins.SitewaertsDocumentViewer is undefined on windows 10. Anyone could help? I've checked it in deviceready event.
