### ISSUE TITLE
how to install in ionic app?

### ISSUE THREAD

**Issue by jose2007kj** [sitewaerts/cordova-plugin-document-viewer#31]
sir,i would like to use in ionic app,how shall i install it

**Comment by regnete** [comment]
I havn't ever used ionic. so i don't have inow how to answer your question.


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 07.11.2016 um 11:43 schrieb KJ JOSE <notifications@github.com<mailto:notifications@github.com>>:


sir,i would like to use in ionic app,how shall i install it

-

**Comment by jose2007kj** [comment]
ok.. sir   thanks for your replay
