### ISSUE TITLE
Spaces not supported in the filename

### ISSUE THREAD

**Issue by dylanvdmerwe** [sitewaerts/cordova-plugin-document-viewer#32]
When opening a file that has spaces in it, the plugin does not handle the filename correctly: 
```
Error in SitewaertsDocumentViewer.viewDocument(): invalid file url 'assets/documents/ProductDeployment/Anti Ram/kb2-01-00-00-00.pdf' or no viewer for mime type 'application/pdf'
```

Filepath example: `assets/documents/ProductDeployment/Anti Ram/kb2-01-00-00-00.pdf`
Path that works: `assets/documents/ProductDeployment/Anti-Ram/kb2-01-00-00-00.pdf`

Tested on iOS 10.1.

**Comment by Iyashu5040** [comment]
Also having this issue. Any space anywhere in the path causes that error. I'm constantly having to rename the documents I receive from the client to work around this quirk.

**Comment by dylanvdmerwe** [comment]
This really should not be labelled as an enhancement. It's a bug.

**Comment by regnete** [comment]
Sorry, but we currently do not have the capacities to work on this issue.
Anybody out there to provide a pull request?
