### ISSUE TITLE
Preview panel not refresh the data

### ISSUE THREAD

**Issue by rchowdhe** [sitewaerts/cordova-plugin-document-viewer#33]
I am using document viewer to show  pulled data from server side, against the selected record.

Initially pulled data correctly display in viewer when it shows page wise.
Issue is when i use preview of all pages in single view it shows old data.

**Comment by regnete** [comment]
Please describe again. I didn't get it.

**Comment by rchowdhe** [comment]
![img_0212](https://cloud.githubusercontent.com/assets/23568939/20617969/5c82bedc-b312-11e6-8fb5-60403b59cfcb.PNG)

I have described issue in screenshot, almost its similar to #13 

Thanks for support

**Comment by regnete** [comment]
- Download a URL to a local file on the device "..../local.pdf"
- Open ".../local.pdf" in the viewer
- Close the viewer
- Download a different URL to the same local file on the device "..../local.pdf" (overwrite)
- Open ".../local.pdf" in the viewer

Is that the way you do it?
Is this case I guess we have a caching issue. Try to change the filename each time you downloada URL to a local file e.g. by adding a timestamp to the filename.

**Comment by regnete** [comment]
duplicate to #13

**Comment by regnete** [comment]
Closed. Please post new messages to #13.
