### ISSUE TITLE
dot('.') in file name - not opening PDF

### ISSUE THREAD

**Issue by pratikgavas** [sitewaerts/cordova-plugin-document-viewer#35]
Some of our pdf contains dot in there file names. If I try to open those files in our plugin, it shows an error that cannot view document.  I know we can change the file name as well, but we are downloading it from server side and we have to store there names for future purpose. So, please if any possibility in our plugin to make this change in future then let me know. Because normally,it is possible to open those PDF files on adobe reader.

Thank you in advance. :)

**Comment by regnete** [comment]
which os?

**Comment by regnete** [comment]
similar to #32

**Comment by pratikgavas** [comment]
ios. yes its similar to #32
