### ISSUE TITLE
Preview panel not refreshing the data

### ISSUE THREAD

**Issue by fuzzy64** [sitewaerts/cordova-plugin-document-viewer#37]
Issue #33 / #13 are closed but not solved.

We are currently facing this issue on an iPad (3. gen) using iOS 9.3.5.

Steps to reproduce:
1. open File A using: `SitewaertsDocumentViewer.viewDocument('fileA.pdf', 'application/pdf');`
2. close the viewer using the Done-Button in the upper left corner
3. open File B using: `SitewaertsDocumentViewer.viewDocument('fileB.pdf', 'application/pdf');`

After opening File B, the preview panel still shows the previews for File A.
The two files have different contents, different names and a different amout of pages.

**Comment by regnete** [comment]
issue is reproducable. will fix it.

**Comment by regnete** [comment]
fixed in 0.8.0
