### ISSUE TITLE
Hyperlinks in PDFs don't work (Android)

### ISSUE THREAD

**Issue by ddellit** [sitewaerts/cordova-plugin-document-viewer#38]
In the Android version, the hyperlinks don't work in the Cleverdox app.  This is a complete showstopper for many applications.

**Comment by regnete** [comment]
The Android viewer app (https://github.com/sitewaerts/android-document-viewer) is absed on MuPDF (http://www.mupdf.com/).s MuPDFs doesn't supports hyperlinks, so the android viewer cannot support them out of the box either.

Will check if I find someone to implement this.

**Comment by regnete** [comment]
Whcih kind of hyperlink are required?
- external hyperlinks (e.g. http://www.sitewaerts.de, mailto:bill@microsoft.com) ?
- internal links which point to a page inside the same document (e.g. in an embedded table of contents) ?
- any other ?

**Comment by ddellit** [comment]
We need the internal hyperlinks to a table of contents or links to other places within a doc.  I thought most PDF viewers would generally support these.

I did test the muPDF standalone viewer app and it is very similar to the Android viewer app except that muPDF has an extra option (chain icon) to turn on hyperlinks.  But we obviously need it to run the viewer from within our app.

[cid:image001.jpg@01D2733F.2C479BB0]


Best regards
Doug Dellit

Mobile:    +61 419 808 251
  E-mail:    doug@dellit.com.au<mailto:doug@dellit.com.au>
  Skype:    d.dellit

**Comment by regnete** [comment]
Finally I got it. Didn't mention the chain button in MuPDF Viewer before. Thank you for the hint.

**Comment by ddellit** [comment]
Ok cool.  The chain button works but it is not well designed since it highlights all hyperlink in a baby poo brown color.


Best regards
Doug Dellit

Mobile:    +61 419 808 251
  E-mail:    doug@dellit.com.au<mailto:doug@dellit.com.au>
  Skype:    d.dellit

**Comment by ddellit** [comment]
Plus hyperlinks should be turned on by default, not off.


From: Doug Dellit
Sent: Friday, 20 January 2017 5:10 PM
To: 'sitewaerts/cordova-plugin-document-viewer' <reply@reply.github.com>; sitewaerts/cordova-plugin-document-viewer <cordova-plugin-document-viewer@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [sitewaerts/cordova-plugin-document-viewer] Hyperlinks in PDFs don't work (Android) (#38)

Ok cool.  The chain button works but it is not well designed since it highlights all hyperlink in a baby poo brown color.


Best regards
Doug Dellit

Mobile:    +61 419 808 251
  E-mail:    doug@dellit.com.au<mailto:doug@dellit.com.au>
  Skype:    d.dellit

**Comment by regnete** [comment]
Right, But: Why isn't it enabled by default in MuPDF? Could be a perfomance issue.

**Comment by ddellit** [comment]
I doubt it, doesn’t seem to make any difference even with a large doc, but I guess it would be due to external links being disabled by default.


Best regards
Doug Dellit

Mobile:    +61 419 808 251
  E-mail:    doug@dellit.com.au<mailto:doug@dellit.com.au>
  Skype:    d.dellit

**Comment by regnete** [comment]
dont' forget to implement the new  linkHandler api as well
