### ISSUE TITLE
Windows.Data.Pdf Undefined

### ISSUE THREAD

**Issue by obeyda** [sitewaerts/cordova-plugin-document-viewer#42]
I am trying to deploy to windows phone 8.1 and i get this error:
` Unable to get property 'PdfDocument' of undefined or null reference`

the origin is this line: 
`return Windows.Data.Pdf.PdfDocument.loadFromStreamAsync(stream);`

I tested the app on windows 10 and it worked.
any ideas?

![image](https://cloud.githubusercontent.com/assets/15065966/22164737/c1348104-df58-11e6-9625-b1cdcc64fb37.png)

**Comment by regnete** [comment]
Windows 8.1 is supported.
Windows Phone 8.1 is not supported.

If you need it, you have to adapt the code. I'm looking forward to your pull request.
