### ISSUE TITLE
Add to ionic native

### ISSUE THREAD

**Issue by dylanvdmerwe** [sitewaerts/cordova-plugin-document-viewer#46]
It would be awesome if this plugin had a wrapper on [ionic native](http://ionicframework.com/docs/v2/native/). 

Would be a great uptake in usage as well :)

**Comment by regnete** [comment]
I have no experience in working with ionic or ionic native. could you fork and then provide a pull request?

**Comment by SebastianSchirmer** [comment]
@dylanvdmerwe @regnete Felix, It seems this plugin now has an ionic-native wrapper with release 3.7.0, see https://github.com/driftyco/ionic-native/commit/6855fe8

Guess you can close this issue.

**Comment by dylanvdmerwe** [comment]
Yes there is an ionic native wrapper now. Epic!

**Comment by regnete** [comment]
Will the guys at ionic-native automatically take care of api changes?

**Comment by dylanvdmerwe** [comment]
Sometimes yes, however having an ionic native wrapper exposes your plugin to a larger audience and is a representation of your plugin. It may be beneficial from time to time for you to check the status of the wrapper and docs around it.

**Comment by SebastianSchirmer** [comment]
They are trying to keep up but a hint for any api changes underneath would probably be beneficial for them. Not necessary a pull request but a simple issue in their repo for example.
