### ISSUE TITLE
npm -> wrong owner?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sitewaerts/cordova-plugin-document-viewer#47]
Hi!

I use `cordova-check-plugins` module for updating my cordova plugins... But found today:

https://www.npmjs.com/package/de.sitewaerts.cordova.documentviewer has wrong owner..

and I can't update plugin...

```
plugin: de.sitewaerts.cordova.documentviewer
source: npm://de.sitewaerts.cordova.documentviewer
installed version: 0.2.0
remote version: 0.2.1
```

**Comment by regnete** [comment]
As stated in the readme the plugin is published at https://www.npmjs.com/package/cordova-plugin-document-viewer.

The correct plugin id is "cordova-plugin-document-viewer".

The npm publication you mentioned with id " de.sitewaerts.cordova.documentviewer" is outdated and was originally created by someone who forked this plugin. I already tried to contact him without success.
