### ISSUE TITLE
onImpossible

### ISSUE THREAD

**Issue by Kison** [sitewaerts/cordova-plugin-document-viewer#50]
Hi, Nice plugin! Thanks for your work.  Can you provide more details for onImpossible callback? Why it calls and what need to do to fix showing pdf doc? I have tired to use it on android.

**Comment by regnete** [comment]
file not found, unkwnown file extension / mime type, etc.
try to explore the code with a java script debugger, which is very easy on android with chrome.

**Comment by Kison** [comment]
Thanks Felix. Do i need to copy pdf files to specific folder? Will they work if they stores in random folder inside app?

**Comment by Kison** [comment]
I mean is it ok if i use relative urls to docs - ./static/pdfs/58a86e84f9bf1618040000b7.pdf

**Comment by regnete** [comment]
Always use absolute urls as supported by the cordova-file-plugin.

**Comment by Kison** [comment]
Thanks!
