### ISSUE TITLE
Close PDF when application goes in background

### ISSUE THREAD

**Issue by pratikgavas** [sitewaerts/cordova-plugin-document-viewer#52]
Hi,
I want to close PDF when application goes in background and then come to foreground. Is there any possibility which helps us to close PDF programatically(from javascript file)?.
Thank you.

**Comment by regnete** [comment]
Basic idea for implementation:
Listen for pause event: https://cordova.apache.org/docs/en/latest/cordova/events/events.html
Currently we have no callback/method for closing an already openend viewer instance! Should be easy to implement.

```js
var _close;

function onShow(close){
    _close = close;
    document.addEventListener("pause", _close, false);
}

function onClose(){
    if(_close){
      document.removeEventListener("pause", _close) ;
      _close = null;
    }
}

cordova.plugins.SitewaertsDocumentViewer.viewDocument(
    url, mimeType, options, onShow, onClose, onMissingApp, onError);

```

**Comment by regnete** [comment]
Which OS do you need this for?

**Comment by pratikgavas** [comment]
For iOS and Android. But iOS on high priority

**Comment by pratikgavas** [comment]
Not found the solution.... Above implementation not working bro. Please check and revert. My PDF is not closing on pause event

**Comment by regnete** [comment]
As  said before: Currently we have no callback/method for closing an already openend viewer instance! Should be easy to implement.
The pseudo code was just to show how it would work, if we would implement the missing callback.

I already started to implement the missing callback but cannot say when I will finish with that.

**Comment by pratikgavas** [comment]
Ohh fine bro. Thank you for the update :)

**Comment by pratikgavas** [comment]
Hi Mr. Felix,
Can you please tell me till what date this enhancement will be done. Because we have a deadline of 10th march 2017 and this is a security flaw which we can't neglect in our case. Please let me know as soon as possible. 
Thank you.

**Comment by regnete** [comment]
sorry, bu I cannot commit to any deadline as this is non profit project.

**Comment by regnete** [comment]
Checkout the brand new version 0.8.1. We added a new option 'autoClose'
 (https://github.com/sitewaerts/cordova-plugin-document-viewer#options) which will force the behaviour you requested. Forget about the callback code I posted a few days ago.

The feature is supported on iOS, Android and Windows.

Please give feedback if it works as expected.

**Comment by pratikgavas** [comment]
Hi Mr. Felix,

Thank you for this update.  This new version I have tested with iOS and it is working as per our expectation. For me, I made some changes into plugin for closing PDF by using NSNotification  UIApplicationWillForeground and It was properly working. But now I am using version @0.8.1. thank you once again.
