### ISSUE TITLE
Use url (http, https) not file://

### ISSUE THREAD

**Issue by cotorusso** [sitewaerts/cordova-plugin-document-viewer#55]
Can i use this plugin with http or https url and not with file?

**Comment by regnete** [comment]
No. 
See https://github.com/sitewaerts/cordova-plugin-document-viewer#cordova-document-viewer-plugin
See https://github.com/sitewaerts/cordova-plugin-document-viewer#known-issues.

Workaround: 

> Online files reachable via http(s) are not supported. Download them to a temp folder before starting the viewer. You may use the onClose callback to cleanup the temp dir when the viewer is closed.
