### ISSUE TITLE
Required single page view

### ISSUE THREAD

**Issue by MilindSuryawanshi** [sitewaerts/cordova-plugin-document-viewer#57]
I can view the pdf in windows 10 cordova app, 
however my problem is: i want to see the 4/5 page pdf, one by one. Means the view of pdf is single page at a time. as shown in Readme- ios demo screen shots.

I am not seen any option to do so, please suggest, is there any existing way to do.

**Comment by regnete** [comment]
currently the windows viewer supports only one generic view type. ios and android support different view types (single, cover, etc.).

If you turn the windows device in portait mode the generic view will behave simmilar to a single page view. does that fit your needs?

we are not planing to implement a single page view for windows in the near future.

**Comment by MilindSuryawanshi** [comment]
First of all Thanks for providing the pdf plugin for windows.

We required to run the app un landscape mode, so it would be great if we get single page view in landscape mode as well.

Thanks
Milind
