### ISSUE TITLE
Required close function

### ISSUE THREAD

**Issue by MilindSuryawanshi** [sitewaerts/cordova-plugin-document-viewer#58]
I can see the pdf on my device, however i do not want user to press the back button to close the pdf, is there any programmatic way, like any close function similar to viewDocument. Which will close the pdf view?

**Comment by regnete** [comment]
We will add this feature within the next days:
`SitewaertsDocumentViewer.closeDocument(success, error)`

**Comment by regnete** [comment]
featiure available in version 0.9.2
