### ISSUE TITLE
cloud the viewer open a hosted pdf from url?

### ISSUE THREAD

**Issue by jounayd** [sitewaerts/cordova-plugin-document-viewer#6]
I work on a project mainly for android. I fetch pdf url from json response. I need to open those pdf inside embeded pdf viewer. Can i do this with this plugin 
 Thank you

**Comment by regnete** [comment]
Hi joynaid,

yes. The plugin can do this job. You have to store the pdf locally via phonegap file api, then pass the local file to the plugin.

felix


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 25.02.2015 um 22:45 schrieb jounayd <notifications@github.com<mailto:notifications@github.com>>:


I work on a project mainly for android. I fetch pdf url from json response. I need to open those pdf inside embeded pdf viewer. Can i do this with this plugin
Thank you

**Comment by jounayd** [comment]
Thanks i will try this

**Comment by Anujmoglix** [comment]
In my case , I don't want to download that pdf in my phone system then will this plugin view it ?

**Comment by regnete** [comment]
No. You may 
1. download
2. store to local file system
3. view
4. delete from local file system
