### ISSUE TITLE
Password Protect PDF

### ISSUE THREAD

**Issue by ajay81** [sitewaerts/cordova-plugin-document-viewer#62]
Hello,
I want to open password protected file, but unable to do that, a normal pdf file is working fine,
Can you please work on that, it will be better if password will be pass through function before it load, so security will increase for pdf to download from temp directory.

Hope you understand my requirement, No one can download pdf or we can protect them via password.

Thanks in advance

**Comment by regnete** [comment]
I'm not shure if I fully understand your requirement.
- You would like to open password protected pdfs with the plugin
- Password should be somehow passed to viewDocument as plain text

Is that correct?

Which platforms are you playing with?

**Comment by ajay81** [comment]
I am looking for both iOS and Android.
My requirement is I have pdf and do not want anyhow it will be copied, so I though about I will create a pdf with a password and then the password would be saved in database. Now when we open pdf through document viewer, then I will pick that password from database and pass it to pdf so it will be open. if any one available to get password then they did not have password. By this way we can put a security layer over pdf. Hope you will understand what I am looking for.
Thanks

**Comment by regnete** [comment]
I understand. But:
The plugin is designed to view pdfs embedded in the app. I you don't provide a link to the user, where he can download or send the pdf, he won't be able to obtain a copy of the file.

so why do you need password protection?

**Comment by ajay81** [comment]
Thanks for your reply,
Here my requirement is little bit more, I have pdf for books, and they can be increase, I am creating app where user can pick from list of pdfs from server for whom they have authentication.

In future number of pdfs can be increased, even the size of pdfs are too big, so putting them inside app means it will make app size too big. and for new pdf I have to build again and published in App store.

Hope you will understand my requirement, waiting for your reply or suggestion so can finish my app.
Thanks in advance

**Comment by regnete** [comment]
whenever a user wants to view a pdf:
- download pdf from server to a temp file on device
- view temp file in viewer
- delete temp file(s) via onClose handler or when app is started/stopped

to increase performance and avoid duplicate donwloads during a session you should delete temp files only when the app is stopped or started.

temp files are protected against external access on android and iOS. On windows the user may access them via windows explorer (if  knows how to do that).
