### ISSUE TITLE
Cleverdox viewer working incorrect on android

### ISSUE THREAD

**Issue by kotromeo** [sitewaerts/cordova-plugin-document-viewer#63]
When inside cleverdox i'm opening table of content and select chapter - cleverdox viewer closing.
Also when on view of table of contect tap on back button (android back button or back button on top left) cleverdox closing but should return to pdf viewer.

**Comment by kotromeo** [comment]
Working correct when option. autoClose.onPause = false

**Comment by regnete** [comment]
Thank you for your bug report. We published version 1.1.3 of the cleverdox Viewer in the google play store minutes ago. The new version should fix your issue.  Install the update (as soon as it is available) and test again.
