### ISSUE TITLE
Error Document Viewer on Android Nougat

### ISSUE THREAD

**Issue by lounis-ESYSTEMES** [sitewaerts/cordova-plugin-document-viewer#66]
Hello and thanks for you're amazing job,

I experiment a bug in your plugin on android Nougat. While the same code work on other android.

I have the problem when I try to open a PDF file. Problem seem to occur on both function : 

SitewaertsDocumentViewer.canViewDocument() and SitewaertsDocumentViewer.viewDocument()

The error is "Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead." 

Here the console log of errors : 

url of file I want to open :  file:///data/user/0/com.esystemes.wiprez/files/files/wiprez_689/zip/wiprez_689.pdf

Errors :

sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.

publications.js:773 onError :  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.

sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.

sitewaertsdocumentviewer.js:344 Error in SitewaertsDocumentViewer.viewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
_logError @ sitewaertsdocumentviewer.js:344
_onError @ sitewaertsdocumentviewer.js:349
exec.url @ sitewaertsdocumentviewer.js:211
callbackFromNative @ cordova.js:295
processMessage @ cordova.js:1119
processMessages @ cordova.js:1142

publications.js:815 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.

Do you have any ideas ? 
Does anyone else have the same issue ?

Thanks

**Comment by regnete** [comment]
Native device or emulator?
Android version number?
cordova-android version number?
Are you able to reproduce the issue with the sample app?

**Comment by lounis-ESYSTEMES** [comment]
The issue is on native device on an Android 7.0.
The device I test with is a Samsung galaxy S7. But the bug have also been produce on Samsung Galaxy S5 with an Android 7.0.
Cordova Version is 6.5.0.
I'll try the sample app and let you know.

**Comment by lounis-ESYSTEMES** [comment]
Just run the sample app on an Samsung Galaxy S7 with Android 7.0.

Have the same problem.

Here an extract of the logs of the sample app : 

returning file:///data/user/0/io.cordova.hellocordova/files/ / file:///data/user/0/io.cordova.hellocordova/files/ / file:///data/user/0/io.cordova.hellocordova/files/ as private data dir
common.js:281 resolving source file:///android_asset/www/test01.pdf
common.js:286 copying file:///android_asset/www/test01.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01.docx
common.js:286 copying file:///android_asset/www/test01.docx to file:///data/user/0/io.cordova.hellocordova/files/test01.docx
common.js:281 resolving source file:///android_asset/www/test01_onepage.pdf
common.js:286 copying file:///android_asset/www/test01_onepage.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_onepage.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01_twopages.pdf
common.js:286 copying file:///android_asset/www/test01_twopages.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_twopages.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01_threepages.pdf
common.js:286 copying file:///android_asset/www/test01_threepages.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_threepages.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01_mixedpages.pdf
common.js:286 copying file:///android_asset/www/test01_mixedpages.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_mixedpages.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01_manypages.pdf
common.js:286 copying file:///android_asset/www/test01_manypages.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_manypages.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:281 resolving source file:///android_asset/www/test01_pdfwithlinks.pdf
common.js:286 copying file:///android_asset/www/test01_pdfwithlinks.pdf to file:///data/user/0/io.cordova.hellocordova/files/test01_pdfwithlinks.pdf
sitewaertsdocumentviewer.js:209 Error in SitewaertsDocumentViewer.canViewDocument():  Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.
common.js:368 Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead.

Hope it will help. 

Same error : "Tried to perform an IO operation on the WebCore thread. Use CordovaInterface.getThreadPool() instead." 

Can do something else to help ?

**Comment by lounis-ESYSTEMES** [comment]
Any idea ? 

I can not be the only one with this bug. Anyone else ?

**Comment by regnete** [comment]
fixed in 0.9.3

**Comment by lounis-ESYSTEMES** [comment]
Nice, seem to be perfect ! Thanks
