### ISSUE TITLE
Error building Android app . Duplicated FileProvider in manifest.xml 

### ISSUE THREAD

**Issue by Makaveli17** [sitewaerts/cordova-plugin-document-viewer#68]
Hi,

I've the cordova-plugin-camera and the cordova-plugin-document-viewer installed. 
I can't  build my android app because these two plugins add the same provider in the android manifest. 
here a sample of my manifest file after a ` cordova build android` : 
```
<provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
       <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
</provider>
<provider android:authorities="com.invokit.mobile.DocumentViewerPlugin.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
        <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/documentviewer_file_paths" />
</provider>
```
During build, the following error occurres:

> AndroidManifest.xml:15:9-17:20 Error:
> Element provider#android.support.v4.content.FileProvider at AndroidManifest.xml:15:9-17:20 duplicated with element declared at AndroidManifest.xml:12:9-14:20

Did you have a fix for solve this problem?

Thanks !

**Comment by regnete** [comment]
Fixed in 0.9.3. See https://github.com/sitewaerts/cordova-plugin-document-viewer/pull/69
