### ISSUE TITLE
Open PDF on first page

### ISSUE THREAD

**Issue by foag** [sitewaerts/cordova-plugin-document-viewer#72]
Android, Ionic. 

It seems as if autoClose-option is ignored when opening a document and then closing. The viewer always opens on the same page as when closed, indicating to me it was paused rather than actually closed. 

Are there any optional way to force viewer to always open on first page as opposed to remember last page viewed?

**Comment by regnete** [comment]
option {page: 1} could be used to explicitly open the first page. but this feature is currently only supported on iOS.

see https://github.com/sitewaerts/cordova-plugin-document-viewer#ios

duplicate to https://github.com/sitewaerts/cordova-plugin-document-viewer/issues/9

**Comment by foag** [comment]
The issue I'm reporting is not to open a specific page (although that's what I want in the end), it's that the explicitly set option autoClose is ignored.

There's no indication in the docs that it's a platform specific option. As I understand it autoClose is there to force the viewer to close instead of pause, which doesn't seem to have any effect.

**Comment by regnete** [comment]
Are you using the cleverdox Viewer App 1.2.0?
