### ISSUE TITLE
viewing PDF is resizing webview 

### ISSUE THREAD

**Issue by ninjamonkno1** [sitewaerts/cordova-plugin-document-viewer#73]
Before viewing pdf 

> window.innerWidth
< 1024

![screen shot 2017-06-16 at 13 53 59](https://user-images.githubusercontent.com/833183/27227567-e5dd897c-529b-11e7-8e7b-9552d61707ee.png)

After pdf is opened and closed

> window.innerWidth
< 768

![screen shot 2017-06-16 at 13 53 22](https://user-images.githubusercontent.com/833183/27227587-f8497602-529b-11e7-8569-6be2ffdb7483.png)

Sorry for the blurry screenshots but it's client data but you get the picture hopefully.

**Comment by regnete** [comment]
Are you able to reproduce the issue on a physical device or in emulator only?

Are you able to reproduce the issue with our sample app?

**Comment by ninjamonkno1** [comment]
I can confirm that the issue was on on the emulator and it works perfectly on the device.
