### ISSUE TITLE
Build failed for Android 

### ISSUE THREAD

**Issue by praveenpds** [sitewaerts/cordova-plugin-document-viewer#74]
**cmd > ionic run android** 

D:\Mobile~~~\platforms\android\src\de\sitewaerts\cordova\documentviewer\DocumentViewerPlugin.java:683: error: cannot find symbol
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.N;
                                                           ^
  symbol:   variable N
  location: class VERSION_CODES

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

**>ionic info**

Your system information:

 ordova CLI: 6.3.1
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v4.6.0
Xcode version: Not installed

**ionic platform  ?**
Installed platforms:
  android 5.2.2
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  browser ~4.1.0
  firefoxos ~3.6.3
  webos ~3.7.0
  windows ~4.4.0
  wp8 ~3.8.2 (deprecated)

**Comment by regnete** [comment]
please try again with cordova android 6.2.3
you are currently using cordova android 5.2.2
