### ISSUE TITLE
can we install muPDF app with in our app

### ISSUE THREAD

**Issue by ajay81** [sitewaerts/cordova-plugin-document-viewer#75]
First, its great plugin, Works fine on iOS
But while working on Android, its create build error, with push notification plugin. some jar file conflicts, don't know how to resolve it.

My question is about muPDF  license restrictions, as we have to install another app. That is necessary to view PDF,  so can we install this with installation of our app, So user did not required again to install required muPDF app. 

It will be better if your muPDF app install when user trying to install our app. Can this possible? if yes then how?

**Comment by regnete** [comment]
your build error: please create separate issue with more information.

muPDF: One App cannot automatically install another app. So the answer is: No.
