### ISSUE TITLE
Vertical scrolling?

### ISSUE THREAD

**Issue by joshterrill** [sitewaerts/cordova-plugin-document-viewer#79]
It seems reasonable to implement an optional for vertical scrolling / horizontal scrolling. Will vertical scrolling be implemented?

**Comment by regnete** [comment]
vertical scrolling is implemented for the windows platform only. horizontal scrolling is implemented for android and ios.
we are currently not planing to implement new scrolling features.

**Comment by joshterrill** [comment]
I’m looking for vertical scrolling on IOS. Any idea when it will come out? Is there an experimental branch that this currently exists on?

Josh Terrill

**Comment by joshterrill** [comment]
I misread your comment, so you're not planning on implementing any vertical scrolling on android and IOS?

**Comment by joshterrill** [comment]
A couple more questions, if you're not planning on integrating vertical scroll for iOS/android, may I ask why? Is it because technically speaking it's not possible / very difficult to do? Or is it because the feature itself does not align with the goal of the repo, therefore you don't want to add it? If someone did implement an option for vertical scroll on iOS/android, would you accept it?

**Comment by regnete** [comment]
May be someone already implemented this feature in a github fork. You would have to check that out on your own.

Any pull requests are welcome. They need to be documented and tested. We prefer implementaions that cover windows, android and ios, but implementations for one or two platforms are also welcome.

**Comment by joshterrill** [comment]
Okay. This specific implementation would cover that, because the feature is already available and implemented in one, and not the other two. I’ll see what it will take if I can’t find another library to do it.

**Comment by connor-odoherty** [comment]
Any update on this?

Has anyone found a fork with vertical scrolling enabled?
