### ISSUE TITLE
Cannot fully scroll table of contents in landscape mode

### ISSUE THREAD

**Issue by regnete** [sitewaerts/cordova-plugin-document-viewer#8]
it looks like the height of the scrolling frame is to big. Threrefor the list of entries cannot be scrolled to the end.

**Comment by regnete** [comment]
@phibo23: Would you please have alook at this issue?

**Comment by phibo23** [comment]
Hi, sorry for the late reply. I'm currently quite busy with other projects. I'll try to find time to look into it next week.
