### ISSUE TITLE
Cannot init frame, error on viewDocument

### ISSUE THREAD

**Issue by ofx-tgardner** [sitewaerts/cordova-plugin-document-viewer#81]
canViewDocument returns true for my file, but on opening I get an error.
The message states "cannot init frame", but the error description object within states:
  "Object doesn't support property or method 'replace'"

Not sure what to do about this.

OS: Windows 10
Cordova ver: 5.4.1

**Comment by regnete** [comment]
may be the url you pass in is not a valid string?
