### ISSUE TITLE
Android does not work

### ISSUE THREAD

**Issue by code-coder** [sitewaerts/cordova-plugin-document-viewer#83]
I couldn't open pdf in android.
I used the pdf path 'assets/data/myFile.pdf'.
And the error message is : Relative URIs are not supported.
Ios runs well.
I am very confused.
Does anyone meet the same problem?

Thanks.

**Comment by regnete** [comment]
'assets/data/myFile.pdf' is not an absolute url. have a look at the sample app.

you could use window.resolveLocalFileSystemURL or prepend a vaild path from the cordova file constants (cordova.file.*).

**Comment by thesurya9** [comment]
Where is the sample app ?? 
"you could use window.resolveLocalFileSystemURL or prepend a vaild path from the cordova file constants (cordova.file.*)." 
please explain this point. 
Please help.

**Comment by regnete** [comment]
sample app is linked in the docs: https://github.com/sitewaerts/cordova-plugin-document-viewer#using-the-plugin

Sorry, I have no capacities on teaching you cordova basics.

**Comment by thesurya9** [comment]
Okay thank U . (y)

**Comment by PixelShoot** [comment]
Correct path for android is 'file:///android_asset/www/assets/'

**Comment by ketchup208** [comment]
what is the path for ios ?

**Comment by PixelShoot** [comment]
@ketchup208 I'm using this code for IOS                                                                                                    `baseUrl = location.href.replace("/index.html", "");                                 this.document.viewDocument(baseUrl + '/assets/your-file.pdf', 'application/pdf', {title: 'your-file-title'});`

**Comment by ketchup208** [comment]
Thank you, i will test it all and maybe submit a pr to change the docs.

**Comment by jimfilippou** [comment]
This is **not** fixed

**Comment by jimfilippou** [comment]
Here is a **patch**
```typescript
 figureOutFile(file: string) {
    if (this.platform.is('ios')) {
      const baseUrl = location.href.replace('/index.html', '');
      return baseUrl + `/assets/${file}`;
    }
    if (this.platform.is('android')) {
      return `file:///android_asset/www/assets/${file}`;
    }
  }
```
