### ISSUE TITLE
The LinkHandler for IOS only works in single page view

### ISSUE THREAD

**Issue by andreasekberg83** [sitewaerts/cordova-plugin-document-viewer#84]
Is this a hard fix or just forgotten to make the LinkHandler work with the other two views? 

BR /A

**Comment by regnete** [comment]
ooops.  SHould be there.
Currently we don't have capacities. Will be fixed, but I don't know when. So if you are able to fix it: pull request are welcome.

**Comment by regnete** [comment]
fixed in version 0.9.6
