### ISSUE TITLE
No email option in iOS

### ISSUE THREAD

**Issue by veto-cearl** [sitewaerts/cordova-plugin-document-viewer#86]
Is the send to email option available in iOS? There is no email button in the reader toolbar even though I specify the email option. I am using the Ionic native wrapper. Is there additional configuration necessary or does it just not work in iOS?

**Comment by veto-cearl** [comment]
Email button shows on iPhone 6 Plus but not showing on iPad Air. Both running iOS 10.3.3.

**Comment by regnete** [comment]
Email account/client configured?


Felix Schauerte
sitewaerts GmbH
www.sitewaerts.de<http://www.sitewaerts.de>

Am 03.11.2017 um 20:17 schrieb Carl Earl <notifications@github.com<mailto:notifications@github.com>>:


Email button shows on iPhone 6 Plus but not showing on iPad Air. Both running iOS 10.3.3.

-

**Comment by veto-cearl** [comment]
No. That was the problem. Completely forgot it was disabled on this test device. Should've checked that. Thanks for the fast response.
