### ISSUE TITLE
cordova.plugins.SitewaertsDocumentViewer is not object

### ISSUE THREAD

**Issue by astics** [sitewaerts/cordova-plugin-document-viewer#88]
I have installed cordova-plugin-document-viewer and try to access but : cordova.plugins.SitewaertsDocumentViewer return undefined.

I checked : cordova plugin -ls ; it show cordova-plugin-document-viewer in the list.
my code:
<!DOCTYPE html>

<html>
    <head>
        
        
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        
        <button class="open">Open</button>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript">
        	$(document).ready(function(){
        		alert('ready');
                var options = {
                    title: "Test",
                    documentView : {
                        closeLabel : 'CLOSE'
                    },
                    navigationView : {
                        closeLabel : 'CLOSE'
                    },
                    email : {
                        enabled : false
                    },
                    print : {
                        enabled : false
                    },
                    openWith : {
                        enabled : false
                    },
                    bookmarks : {
                        enabled : false
                    },
                    search : {
                        enabled : true
                    },
                    autoClose: {
                        onPause : false
                    }
                }
                var url = '123.pdf';
                if(cordova.plugins && cordova.plugins.SitewaertsDocumentViewer){
                    alert('plugins');
                }else{
                	alert('no plugins');
                }
                // cordova.plugins.SitewaertsDocumentViewer.canViewDocument(url,  'application/pdf', options, onPossible, onMissingApp, onImpossible, onError);
                $("#open").click(function(){
                	alert('click');
                    if(cordova.plugins.SitewaertsDocumentViewer.viewDocument){
                    cordova.plugins.SitewaertsDocumentViewer.viewDocument(url,  'application/pdf', options, onShow, onClose, onMissingApp, onError);
                    }else{
                        alert("not a viewDocument");
                    }
                });
            });
                function onPossible(){
                  alert('document can be shown');
                  //e.g. track document usage
                }
                function onMissingApp(appId, installer)
                {
                    if(confirm("Do you want to install the free PDF Viewer App "
                            + appId + " for Android?"))
                    {
                        installer();
                    }
                }
                function onImpossible(){
                  alert('document cannot be shown');
                  //e.g. track document usage
                }
                function onError(error){
                  alert(error);
                  alert("Sorry! Cannot show document.");
                }
                function onShow(){
                  alert('document shown');
                  //e.g. track document usage
                }
                function onClose(){
                  alert('document closed');
                  //e.g. remove temp files
                }
                // cordova.plugins.SitewaertsDocumentViewer.closeDocument(onClose, onError);
                function onClose(url){
                    if(url)
                        alert('closed viewer document ' + url);
                    else
                        alert('viewer not open');
                }
        </script>
    </body>
</html>

**Comment by astics** [comment]
`<!DOCTYPE html>

<html>
    <head>
        
        
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        
        <button class="open">Open</button>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript">
        	$(document).ready(function(){
        		alert('ready');
                var options = {
                    title: "Test",
                    documentView : {
                        closeLabel : 'CLOSE'
                    },
                    navigationView : {
                        closeLabel : 'CLOSE'
                    },
                    email : {
                        enabled : false
                    },
                    print : {
                        enabled : false
                    },
                    openWith : {
                        enabled : false
                    },
                    bookmarks : {
                        enabled : false
                    },
                    search : {
                        enabled : true
                    },
                    autoClose: {
                        onPause : false
                    }
                }
                var url = '123.pdf';
                if(cordova.plugins && cordova.plugins.SitewaertsDocumentViewer){
                    alert('plugins');
                }else{
                	alert('no plugins');
                }
                // cordova.plugins.SitewaertsDocumentViewer.canViewDocument(url,  'application/pdf', options, onPossible, onMissingApp, onImpossible, onError);
                $("#open").click(function(){
                	alert('click');
                    if(cordova.plugins.SitewaertsDocumentViewer.viewDocument){
                    cordova.plugins.SitewaertsDocumentViewer.viewDocument(url,  'application/pdf', options, onShow, onClose, onMissingApp, onError);
                    }else{
                        alert("not a viewDocument");
                    }
                });
            });
                function onPossible(){
                  alert('document can be shown');
                  //e.g. track document usage
                }
                function onMissingApp(appId, installer)
                {
                    if(confirm("Do you want to install the free PDF Viewer App "
                            + appId + " for Android?"))
                    {
                        installer();
                    }
                }
                function onImpossible(){
                  alert('document cannot be shown');
                  //e.g. track document usage
                }
                function onError(error){
                  alert(error);
                  alert("Sorry! Cannot show document.");
                }
                function onShow(){
                  alert('document shown');
                  //e.g. track document usage
                }
                function onClose(){
                  alert('document closed');
                  //e.g. remove temp files
                }
                // cordova.plugins.SitewaertsDocumentViewer.closeDocument(onClose, onError);
                function onClose(url){
                    if(url)
                        alert('closed viewer document ' + url);
                    else
                        alert('viewer not open');
                }
        </script>
    </body>
</html>
`

**Comment by regnete** [comment]
respect the deviceready event from cordova.


Am 11.11.2017 um 13:01 schrieb astics <notifications@github.com<mailto:notifications@github.com>>:


`

<title>Hello World</title> Open <script type="text/javascript" src="cordova.js"></script> <script type="text/javascript" src="js/index.js"></script> <script type="text/javascript" src="js/jquery.min.js"></script> <script type="text/javascript"> $(document).ready(function(){ alert('ready'); var options = { title: "Test", documentView : { closeLabel : 'CLOSE' }, navigationView : { closeLabel : 'CLOSE' }, email : { enabled : false }, print : { enabled : false }, openWith : { enabled : false }, bookmarks : { enabled : false }, search : { enabled : true }, autoClose: { onPause : false } } var url = '123.pdf'; if(cordova.plugins && cordova.plugins.SitewaertsDocumentViewer){ alert('plugins'); }else{ alert('no plugins'); } // cordova.plugins.SitewaertsDocumentViewer.canViewDocument(url, 'application/pdf', options, onPossible, onMissingApp, onImpossible, onError); $("#open").click(function(){ alert('click'); if(cordova.plugins.SitewaertsDocumentViewer.viewDocument){ cordova.plugins.SitewaertsDocumentViewer.viewDocument(url, 'application/pdf', options, onShow, onClose, onMissingApp, onError); }else{ alert("not a viewDocument"); } }); }); function onPossible(){ alert('document can be shown'); //e.g. track document usage } function onMissingApp(appId, installer) { if(confirm("Do you want to install the free PDF Viewer App " + appId + " for Android?")) { installer(); } } function onImpossible(){ alert('document cannot be shown'); //e.g. track document usage } function onError(error){ alert(error); alert("Sorry! Cannot show document."); } function onShow(){ alert('document shown'); //e.g. track document usage } function onClose(){ alert('document closed'); //e.g. remove temp files } // cordova.plugins.SitewaertsDocumentViewer.closeDocument(onClose, onError); function onClose(url){ if(url) alert('closed viewer document ' + url); else alert('viewer not open'); } </script> `

-

**Comment by astics** [comment]
thanks....you save my time.
