### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by anthonydesch** [sitewaerts/cordova-plugin-document-viewer#89]
I have a document in the www of my app. how to create the link in the html to open it. My tests are unsuccessful :-(
I use adobe phonegap to generate the application. I add the following line in config.xml

`<plugin spec="https://github.com/sitewaerts/cordova-plugin-document-viewer" />`

And the link does not work: nothing happens.

`<a href="#" onclick="cordova.plugins.SitewaertsDocumentViewer.viewDocument('pdf/test.pdf')"><div class="liste">test 1</div></a>
    <a href="#" onclick="cordova.plugins.SitewaertsDocumentViewer.viewDocument('pdf/test.pdf')"><div class="liste">test 2</div></a>
    <a href="#" onclick="cordova.plugins.SitewaertsDocumentViewer.viewDocument('assets/pdf/test.pdf')"><div class="liste">test 3</div></a>
    <a href="#" onclick="cordova.plugins.SitewaertsDocumentViewer.viewDocument('file:///android_asset/www/pdf/test.pdf')"><div class="liste">test 4</div></a>`

Thank you for your help

**Comment by regnete** [comment]
Please use a debugger to find out what you are doing wrong. For Android this would be developer tools in Chrome Browser.
Check the sample app for reference.

**Comment by anthonydesch** [comment]
My emulator does not work because I use a linux os. What is the right way to write the link?
