### ISSUE TITLE
Open at a given page Number?

### ISSUE THREAD

**Issue by hirenhcm** [sitewaerts/cordova-plugin-document-viewer#9]
Does this plugin have the option to open a PDF file at a given page number?

**Comment by regnete** [comment]
No, but feel free to add this feature.

Felix


Am 19.05.2015 um 07:42 schrieb Hiren C. Mistry <notifications@github.com<mailto:notifications@github.com>>:


Does this plugin have the option to open a PDF file at a given page number?

**Comment by hirenhcm** [comment]
@regnete Thanks for you reply. Will try to contribute on this feature if time permits. :)

**Comment by regnete** [comment]
Feature now availbale for iOS. Windows and Android still lack support for this feature.

**Comment by apiening** [comment]
Is this feature which works under iOS planned to be implemented for android, too?
I wonder if this is just about adding a parameter to the call of the document viewer or if it is more complicated on android, since an external app is used to display the pdf file?
