### ISSUE TITLE
Problem with HTML5 history on Windows 10

### ISSUE THREAD

**Issue by goffioul** [sitewaerts/cordova-plugin-document-viewer#90]
I'm using this plugin for PDF viewing withing my Cordova/Win10 app. It works fine, except that it interferes with the HTML5 history of the main frame. The way I understand it is as follows:
- cordova app calls (for the first time) "viewDocument"
- plugin creates an <IFRAME> and loads "ms-appx://.../www/viewer.html"
- when the user closes the viewer, the plugin navigate the <IFRAME> to a blank URL and hides the iframe's container

Now the problem is that in the main frame, the HTML5 history object is now operating on the iframe. If the main frame calls "history.back()", this will actually change the URL within the iframe back to ".../viewer.html". If the main frame calls again "history.back()", it will now operate on the main frame: my guess is that it's because the iframe has reached the first entry in its own history stack, and there's nothing to go back to within that frame.

Is there a workaround for that problem?

**Comment by regnete** [comment]
you are the first user reporting an issue related to browser history. feel free to implement a workarround. pull requests are always welcome. 

possibly it would help to switch from iframe to inappbrowser plugin?
