### ISSUE TITLE
License

### ISSUE THREAD

**Issue by peardox** [sitewaerts/cordova-plugin-document-viewer#93]
I have completely free (with ads) for droid

My partner wants paid apps for FireOS

Is there any way to embed the PDF reader ONLY FOR zero charge into droid?

Another Q is what if I get a license?

Comments pls

**Comment by regnete** [comment]
Sorry, but I don't understand your requirement. 

You have to respect the MIT license when using this plugin. That means: It's always free. We don't provide any other type of (paid) license.

FireOS is currently not supported and we're not planning to.
