### ISSUE TITLE
Problem with opening PDF's from cordova.file.dataDirectory on Windows

### ISSUE THREAD

**Issue by BigJenson** [sitewaerts/cordova-plugin-document-viewer#94]
Hi,

i currently can't open PDF's from the cordova.file.dataDirectory on Windows10.
The Path of the File is ms-appdata:///local/.../attachment123423535 (files are renamed to match id's from a Database).
the pfdviewer.js throws the following exception at line 1222: 

> cannot load outline for pdf ms-appdata:///local/app-files/attachment5a4caa6944142 UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "ms-appdata:///local/app-files/attachment5a4caa6944142

With IOS its working just fine. Any ideas what is going wrong?

**Comment by regnete** [comment]
May be the missing file name extension (.pdf) is causing this issue?

**Comment by BigJenson** [comment]
I've added the extension (.pdf) back to the files, still the same exception.

**Comment by regnete** [comment]
You could try a different storage location. See our sample app for an example. May be that helps...
