### ISSUE TITLE
Invalid file url , cannot access file

### ISSUE THREAD

**Issue by richie50** [sitewaerts/cordova-plugin-document-viewer#95]
I'm not sure why, but the path i'm passing in is valid.  I have the right access to read and write to this file. Any insight as to why this might be happening

file:///storage/sdcard/Android/data/XXXXXXXX/files/presentations/1269/abc/Https_testing.pdf

 {message: "invalid file url 'file:///storage/sdcard/Android/d…pdf' or no viewer for mime type 'application/pdf'", details: {…}}details: {status: 0, message: "File 'file:///storage/sdcard/Android/data/com.inde…esting.pdf' is not available (cannot access file)"}message: "invalid file url 'file:///storage/sdcard/Android/data/dddddd/files/presentations/1269/abc/Https_testing.pdf' or no viewer for mime type 'application/pdf'"__proto__: Object
_logError @ sitewaertsdocumentviewer.js:344
_onError @ sitewaertsdocumentviewer.js:349
(anonymous) @ sitewaertsdocumentviewer.js:431
exec.url @ sitewaertsdocumentviewer.js:204
callbackFromNative @ cordova.js:294
(anonymous) @ VM584:1
androidExec @ cordova.js:971
canViewDocument @ sitewaertsdocumentviewer.js:177
viewDocument @ sitewaertsdocumentviewer.js:365
webpackJsonp../src/pages/meeting/meeting.ts.MeetingPage.openPDFOnDeviceUsingDocViewer @ main.js:303344
webpackJsonp../src/pages/meeting/meeting.ts.MeetingPage.handleOpenLink @ main.js:303285
(anonymous) @ main.js:303233
postMessage (async)
onclick @ android.html:8

**Comment by regnete** [comment]
The file you are passing in cannot be accessed.

see https://github.com/sitewaerts/cordova-plugin-document-viewer/blob/8a6958c2643a80ab5d995d3a36d49bfe5589fad3/src/android/de/sitewaerts/cordova/documentviewer/DocumentViewerPlugin.java#L850

the  String fileArg is exactly the file url you pass in. the method returns a file object, but that files exists method returns false. you should debug that.

could be related to file permissions or upper/lower case letters in the url. or something else.

**Comment by rasheeek** [comment]
Still facing the same issue
