### ISSUE TITLE
Optimize Plugin for iPhone X

### ISSUE THREAD

**Issue by kceb** [sitewaerts/cordova-plugin-document-viewer#97]
Currently the document viewer has extra padding in the statusbar location of the iPhone X. This is not a breaking issue, but it may interfere with UI/UX

I have attached a screenshot. Note the top statusbar area:

![img_0247](https://user-images.githubusercontent.com/6913202/35070911-daf04d6e-fb93-11e7-839c-0ccfc58bb67c.PNG)

Reproduction Steps:

Cordova Version: 7.0.1
Plugin Version: 0.9.7
1. Install plugin
2. Deploy to iPhone X
3. Open a local file with mime type 'application/pdf'
4. View statusbar

**Comment by venuchiluveru** [comment]
I am also facing the same issue with mime type 'application/pdf' in iPhone X
![2018-01-22 18-06-29 screenshot](https://user-images.githubusercontent.com/25214773/35221147-f67cb852-ff70-11e7-8b09-3ca8d6aadf89.jpg)

**Comment by arcanys-ivan** [comment]
any updates on this issue?

**Comment by regnete** [comment]
We are currently not planing to add support for phones. The plugin mainly targets tablets.

**Comment by mhughes2k** [comment]
Unfortunately it's one that does seem to work nicely. 

Is this more an issue relating to the VFR Reader (which appears to be deprecated)?

Would you be considering moving from VFR to the UXReader PDF Framework for iOS? (https://github.com/vfr/UXReader-iOS)

**Comment by JRR-OSU** [comment]
@regnete You should fix this issue as it violates Apple's safe area constraints. When the new iPads are released, this UI issue will be present on those.

**Comment by CodingAnonymous** [comment]
Any news? Would be highly appreciated!

**Comment by CodingAnonymous** [comment]
> Unfortunately it's one that does seem to work nicely.
> 
> Is this more an issue relating to the VFR Reader (which appears to be deprecated)?
> 
> Would you be considering moving from VFR to the UXReader PDF Framework for iOS? (https://github.com/vfr/UXReader-iOS)

I think that would be the right choice, would be very sad if apple declines the app to the app store because it violates Apple's safe area constraints

**Comment by JRR-OSU** [comment]
@CodingAnonymous

I can submit a PR and try and fix it when I have some extra time. Would only take a bit.

**Comment by CodingAnonymous** [comment]
@JRR-OSU 

That would be awesome! Thank you very much in advance!

**Comment by CodingAnonymous** [comment]
@JRR-OSU 

If you have a version to test, I would like to help!

**Comment by JRR-OSU** [comment]
> @JRR-OSU
> 
> If you have a version to test, I would like to help!

Just fixed it for you :) Check out PR #132. That should do the trick.

**Comment by CodingAnonymous** [comment]
Thanks @JRR-OSU , I can't open any document now, is this happening to you, too?

**Comment by JRR-OSU** [comment]
@CodingAnonymous I'm still able to open documents.

**Comment by CodingAnonymous** [comment]
@JRR-OSU I get following error: 
Error in SitewaertsDocumentViewer.viewDocument():  
"invalid file url 'function () {↵    if (this.nativeURL) {↵        return this.nativeURL;↵    }↵    /…"

**Comment by JRR-OSU** [comment]
@CodingAnonymous Can you reproduce in a small project and upload it as a zip or post on here?

**Comment by CodingAnonymous** [comment]
Thanks for your advice, I figured the path out. I use phonegap build and have the following line:
`<plugin spec="https://github.com/JRR-OSU/cordova-plugin-document-viewer.git" source="git" />`
Sadly it is the same problem as before with the bad UI on the iPhone X, very likely your edited file isn't loaded...
