### ISSUE TITLE
Error in Success callbackId: FileTransfer32755790 : TypeError: Cannot read property 'viewDocument' of undefined.

### ISSUE THREAD

**Issue by nikhilka08** [sitewaerts/cordova-plugin-document-viewer#98]
*Error in Success callbackId: FileTransfer32755790 : TypeError: Cannot read property 'viewDocument' of undefined*

I am able to download file to localstorage of phone with filetransfer plugin. This is my code:

```

openFile: function(e) {
            e.preventDefault();
            var pdf_url = api_url + '/w/document.php?document_id=' + this.model.attributes.document_id + 
                '&token=' + window.api_token +
                '&display=true';
            /* var ref = window.open(pdf_url, '_blank', 'location=yes');  */
            console.log(pdf_url);
            var filetransfer = new FileTransfer();
            var uri = encodeURI(pdf_url);


            filetransfer.download(
                uri,
                cordova.file.externalApplicationStorageDirectory+'workorder.pdf',
                function(entry){
                    console.log('download complete' + entry.toURL());
                    var pdffile = entry.toURL();
                  cordova.plugins.SitewaertsDocumentViewer.viewDocument(
                        pdffile , "application/pdf", "title:PDF", function onShow(){}, function onClose(){}, function onMissingApp(){},
                        function onError(){ window.console.log(error);}, function linkHandlers(){}
                    );
                },
                function(error) {
                    console.log('download error source ' + error.source);
                    console.log('download error target ' + error.target);
                    console.log('upload error code is ' + error.code);
                  }
            );    

        }
```

This is the error in console:
`download completefile:///storage/emulated/0/Android/data/com.adobe.phonegap.app/workorder.pdf
[phonegap] [console.log] Error in Success callbackId: FileTransfer32755790 : TypeError: Cannot read property 'viewDocument' of undefined
`

**Comment by regnete** [comment]
did you really load the plugin cordova-plugin-document-viewer via config.xml? please double check.

**Comment by nikhilka08** [comment]
@regnete Yes, plugin is added without any error and plugin is added in my config.xml, package.json and in plugins folder

**Comment by regnete** [comment]
I guess this issue has no dependency to the filetransfer plugin.
Is your code executed **after** the deviceready event?
Are you using the latest version of the plugin from npm?
attach your device to a computer and use the chrome debugger to find out whats going wrong.

**Comment by nikhilka08** [comment]
@regnete Yes the code is executed after deviceready event because FileTransfer plugin is working fine and downloading the pdf to local storage of device. I am using the latest version of this plugin.
And chrome debugger shows the same error

**Comment by regnete** [comment]
did you ever try it with `SitewaertsDocumentViewer` instead of `cordova.plugins.SitewaertsDocumentViewer`?
