### ISSUE TITLE
Android cloud print error: Uncaught TypeError: Cannot read property 'o' of null

### ISSUE THREAD

**Issue by ghost** [sitewaerts/cordova-plugin-document-viewer#99]
We get the error "Uncaught TypeError: Cannot read property 'o' of null" when we press the printing button insight the embedded "Google Cloud Print" dialog in the sitewaerts cleverdox viewer app.

> I/chromium: [INFO:CONSOLE(313)] "Uncaught TypeError: Cannot read property 'o' of null", source: https://www.google.com/cloudprint/client/2161142221-dialog_mobile__de.js (313)

Android-Version: 6.0

cordova-plugin-document-viewer-Version: 0.9.7
cleverdox Viewer for Android-Version: 1.2.0

Is this a known problem?

**Comment by grizzz** [comment]
I found a fix for this problem and created a pull request (https://github.com/sitewaerts/mupdf-for-cleverdox/pull/1) which fixes the error for us.
